- binding/Binding/SKPaint.cs
- binding/Binding/SkiaApi.cs
> Added String Measuring

- .gitignore
- Makefile
new target is to simplify build server configuration to deploy API docs to https://developer.xamarin.com/api/namespace/SkiaSharp/
> added 'assemble-docs' makefile target

- binding/Binding/SKPaint.cs
- binding/Binding/SkiaApi.cs
> Add FilterQuality property on SKPaint

- README.md
Add `clean` and `clean-externals` target documentation to README.
> Update README.md for `clean` targets

- README.md
Add explanation of how to clone the submodules.
> Update README.md with submodule docs

- native-builds/src/SkiaKeeper.c
Added some functions to SkiaKeeper.c to overcome "EntryPointNotFoundException"s
> Updated SkiaKeeper.c to fix "EntryPointNotFound" exceptions

- binding/Binding/Binding.projitems
- binding/Binding/SKRegion.cs
- binding/Binding/SkiaApi.cs
- native-builds/src/SkiaKeeper.c
This changeset add the basic bindings needed for the SKRegion class.
> Add SKRegion support

- binding/Binding/Definitions.cs
- binding/Binding/SKBitmap.cs
- binding/Binding/SkiaApi.cs
- native-builds/src/SkiaKeeper.c
- tests/Tests/SKBasicTypesTest.cs
- tests/Tests/SKBitmapTest.cs
Fulfills https://github.com/mono/SkiaSharp/issues/220.
Requires https://github.com/mono/skia/pull/46
> SKMask support

- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKCanvasViewRendererBase.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKGLViewRendererBase.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/RendererTypes.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKCanvasView.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKGLView.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLSurfaceView.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLSurfaceViewRenderer.cs
- source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLLayer.cs
- source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLView.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Desktop/SKGLControl.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLLayer.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs
- source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKSwapChainPanel.cs
> [WIP] Expose the Current `GRContext`

- source/SkiaSharp.Views/SkiaSharp.Views.Apple/AppleExtensions.cs
> Issue #439

- source/SkiaSharp.Views/SkiaSharp.Views.WPF/SKElement.cs
> Issue #400

- binding/Binding/Properties/SkiaSharpAssemblyInfo.cs
- binding/Binding/SKObject.cs
- build.cake
- source/SkiaSharp.Build.targets
- tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.csproj
- tests/SkiaSharp.NetCore.Tests/SkiaSharp.NetCore.Tests.csproj
- tests/Tests/SKApiTests.cs
Fixed a case where exceptions were thrown in the constructors. Fixes #482
- only dispose the list if the list was actually created
- sign the tests so we can use InternalsVisibleTo
- added a test to identify #482
> Fix bug in SKObject.Dispose

- source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKCanvasView.cs
> iOS SKCanvasView - Disposing UIGraphics context to help GC

- docs/en/FrameworksIndex/skiasharp-views-tizen-1.60.1.xml
- docs/en/SkiaSharp.Views.Tizen/ScalingInfo.xml
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SKTouchHandler.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKCanvasViewRendererBase.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKGLViewRendererBase.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Tizen/SKTouchHandler.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKTouchHandler.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Tizen/ScalingInfo.cs
Some changes to the SKTouchHandler to make future platforms a bit easier.
> Changes to SKTouchHandler

- binding/Binding/Definitions.cs
- build.cake
- Added some overloads to structs
- Added an option to skip building externals to speed up builds that already have the externals built
- Using a macro to help declare the mapping from the C++ type to the C type
- Added correct file headers to the C/C++ files
> Some Improvements

- binding/Binding/Definitions.cs
- binding/Binding/SKCanvas.cs
- binding/Binding/SKPath.cs
- binding/Binding/SKRoundRect.cs
- binding/Binding/SkiaApi.cs
- binding/Binding/Util.cs
- build.cake
- cake/BuildExternals.cake
- tests/Tests/SKCanvasTest.cs
- tests/Tests/SKPathTest.cs
- tests/Tests/SKRoundRectTest.cs
> Binding SkRRect as SKRoundRect

- source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKXamlCanvas.cs
> Make sure to detach static event for UWP

- source/SkiaSharp.Views/SkiaSharp.Views.Gtk/SKWidget.cs
This gives the `SKWidget` for Gtk# a massive performance boost by moving
the creation of the `SKSurface` (and `SKImageInfo`) to the
`CreateDrawingObjects()` method (formally `CreatePixbuf()`).  This makes
it so that these objects aren't being made every render cycle.  That is
what was causing the slowdow.
This also gets rid of the flicker reported in #534; it's flicker from
window dragging & resizing is now on par with that of Cairo's.
Another minor optimization was made, removing the call to
`base.OnExposeEvent()`.  It's not needed and the extra fuction call can
siphon off CPU cycles we'd like to keep.  Some other optimizations can
be made, but most of them probably are very minor.
closes #534
> Improve rendering speed for Gtk#'s SKWidget

- VERSIONS.txt
- scripts/build-linux.sh
- scripts/install-tizen.sh
> Try to reduce native library sizes

- build.cake
> Update to include nuget-validation build.cake

- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKTouchEventArgs.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs
This is for #449. I tried to implement it as easys as possible. I couldn't test it. Didn't get, how to do this.
An alternative would be to use djgtrams suggestions [here](https://forums.xamarin.com/discussion/124185/mouse-wheel-event). He uses Effects to get the wheel events.
> VS bug [#742851](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742851)
> Added mouse wheel handling for Forms.UWP

- build.cake
- cake/BuildExternals.cake
- cake/UpdateDocs.cake
- cake/UtilsManaged.cake
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
This merges #789, but still build the samples on macOS.
> Skip Signing on Public Builds

- .gitmodules
- bootstrapper.ps1
- bootstrapper.sh
- build.cake
- cake/BuildExternals.cake
- cake/UpdateDocs.cake
- scripts/azure-pipelines.yml
Wiki: https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp
> Improving the first-time experience

- binding/Binding/SKTextBlob.cs
- binding/SkiaSharp.OSX/SkiaSharp.OSX.csproj
Haven't tested this yet will do when build has finished
> Spanify SKTextBlobBuilder

- source/SkiaSharp.Views/SkiaSharp.Views.Shared/Extensions.cs
- source/SkiaSharp.Views/SkiaSharp.Views.WPF/SKElement.cs
> Fix #849 : function ToSKPixmap create display artifacts with transparent bitmaps

- scripts/azure-pipelines.yml
Reset the counter for the master branch.
**Bugs Fixed**
- N/A
None.
None.
> Reset the counter for the master branch

- build.cake
- cake/BuildExternals.cake
- cake/UpdateDocs.cake
Added a few tasks to help with docs.
> Add some task to generate docs

- binding/Binding/SKRoundRect.cs
Not quite sure what happened in #995
**Bugs Fixed**
- Resolves #994
None.
None.
> Re-fix the memory leak in round rect

- source/SkiaSharp.Views/SkiaSharp.Views.Android/SKCanvasView.cs
Free memory when the view is detached.
**Bugs Fixed**
- Fixes #1004
None.
None.
> Free memory when the view is detached. Fixes #1004

- binding/Binding/SKShader.cs
- changelogs/HarfBuzzSharp/2.6.1/HarfBuzzSharp.md
- changelogs/SkiaSharp.Views/1.68.1/SkiaSharp.Views.Android.md
- changelogs/SkiaSharp/1.68.1/SkiaSharp.md
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
- scripts/install-openjdk.ps1
- scripts/install-tizen.ps1
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.WPF/SKTouchHandlerElement.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.WPF/SKTouchHandlerWinForms.cs
Describe your changes here. 
**Bugs Fixed**
Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.
Added: 
Changed:
> Final tweaks to prepare for release

- source/SkiaSharp.Views/SkiaSharp.Views.Apple/SKCGSurfaceFactory.cs
Correction of #879. Make sure recreate the memory when the total canvas area changes.
**Bugs Fixed**
- Related to issue #879
None
No crashes when the macOS view resizes.
> Correctly manage the memory for iOS, tvOS, watchOS and macOS views

- binding/Binding/SKObject.cs
`SKObject.DeregisterHandle(...)` now uses `TryRemove` in order to remove handles from the `ConcurrentDictionary`. I kept the logic the same otherwise.
Should there be tests for this besides those that already exist? I might be able to add something if so. Don't know the codebase too well.
**Bugs Fixed**
- #1032 "Possible Leak with static Dictionary SKObject.instances"
None
None
> TryRemove SKObject.instances WeakReferences

- binding/Binding/SkiaApi.generated.cs
- tests/SkiaSharp.Desktop.Tests/Properties/AssemblyInfo.cs
- tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.csproj
- tests/Tests/GRContextTest.cs
- tests/Tests/GlContexts/Wgl/Kernel32.cs
- tests/Tests/GlContexts/Wgl/RECT.cs
- tests/Tests/GlContexts/Wgl/User32.cs
- tests/Tests/GlContexts/Wgl/WNDCLASS.cs
- tests/Tests/GlContexts/Wgl/WindowStyles.cs
- tests/Tests/SKCanvasTest.cs
- tests/Tests/SKSurfaceTest.cs
- utils/SkiaSharpGenerator/Generate/Generator.cs
> Pulling in some changes from other places

- binding/Binding/SKCanvas.cs
- binding/Binding/SKImage.cs
- binding/Binding/SKMatrix.cs
- binding/Binding/SKRoundRect.cs
- binding/Binding/SkiaApi.generated.cs
- binding/libSkiaSharp.json
- tests/Tests/SKCanvasTest.cs
- tests/Tests/SKMatrixTests.cs
Add a few more members for SKCanvas
- DrawArc
- DrawAtlas
- DrawPatch
- DrawRoundRectDifference
- IsClipEmpty and IsClipRect
**Bugs Fixed**
- Fixes #680
Added: 
Changed:
> Add a few more members for SKCanvas

- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKGLViewRendererBase.cs
Unregister  from GetCanvasSize  and GetGRContext  at dispose.
It is added in OnElementChanged
It helps me with
https://github.com/Mapsui/Mapsui/issues/735
**Bugs Fixed**
- Fixes #793
> SKGLViewRenderer dispose corrections

- source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLSurfaceViewRenderer.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLTextureViewRenderer.cs
- source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLLayer.cs
- source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLView.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLLayer.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKGLSurfaceView.cs
Fix issues with buffer samples.
**Bugs Fixed**
- Fixes #1087
None.
Fix issues where the current buffer is not actually set up for the max samples.
> Fix issues with buffer samples

- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
The compliance issues are now under their own area. And fix that weird build error by using an older mono.
**Bugs Fixed**
None.
None.
None.
> Update the build for the new team

- binding/Binding/SKRegion.cs
- binding/Binding/SkiaApi.generated.cs
- changelogs/SkiaSharp/1.68.2/SkiaSharp.md
- tests/Tests/SKRegionTest.cs
Added the remainder of the members for `SKRegion`.
**Bugs Fixed**
- Fixes #1088
- TODO!!!
None. Just new members.
> Added the rest of SKRegion members

- binding/Binding/SKImage.cs
- binding/Binding/SkiaApi.generated.cs
- changelogs/SkiaSharp/1.68.2/SkiaSharp.md
- tests/Tests/SKImageTest.cs
Added some more overloads to `SKImage` to help with GPU textures and lazy images.
**Bugs Fixed**
None.
But, this is related to #1097
TODO.
> Added more from SKImage

- native/android/build.cake
- native/ios/build.cake
- native/linux/build.cake
- native/macos/build.cake
- native/tizen/build.cake
- native/tvos/build.cake
- native/watchos/build.cake
Update expat native library to 2.2.9
**Bugs Fixed**
- Fixes #405 
- Relates to #718
None.
Updating the dependencies.
> Update expat native library to 2.2.9

- VERSIONS.txt
- tools/packages.config
Update cake to 0.37
**Bugs Fixed**
None.
None.
None.
> Update cake to 0.37

- native/uwp/build.cake
- scripts/install-openjdk.ps1
Use the correct URL for OpenJDK on Linux.
**Bugs Fixed**
None.
None.
None.
> Use the correct URL for OpenJDK on Linux

- source/SkiaSharp.Build.targets
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.GTK/SkiaSharp.Views.Forms.GTK.csproj
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SkiaSharp.Views.Forms.Mac.csproj
- tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.csproj
Describe your changes here. 
**Bugs Fixed**
Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.
Added: 
Changed:
> Always reference netstandard

- binding/Binding/SKRotationScaleMatrix.cs
Rename some methods to be more .NET
**Bugs Fixed**
None.
Changes from `FromXxx` to `CreateXxx`.
None.
> Rename some methods to be more .NET

- VERSIONS.txt
- cake/UtilsManaged.cake
- changelogs/HarfBuzzSharp/2.6.1.2/HarfBuzzSharp.md
- changelogs/SkiaSharp.Views.Desktop.Common/1.68.2/SkiaSharp.Views.Desktop.Common.md
- changelogs/SkiaSharp.Views.Forms.GTK/1.68.2/SkiaSharp.Views.Forms.md
- changelogs/SkiaSharp.Views.Forms.WPF/1.68.2/SkiaSharp.Views.Forms.md
- changelogs/SkiaSharp.Views.Forms/1.68.2/SkiaSharp.Views.Forms.breaking.md
- changelogs/SkiaSharp.Views.Forms/1.68.2/SkiaSharp.Views.Forms.md
- changelogs/SkiaSharp.Views/1.68.2/SkiaSharp.Views.Android.md
- changelogs/SkiaSharp.Views/1.68.2/SkiaSharp.Views.Mac.md
- changelogs/SkiaSharp.Views/1.68.2/SkiaSharp.Views.Tizen.md
- changelogs/SkiaSharp.Views/1.68.2/SkiaSharp.Views.UWP.md
- changelogs/SkiaSharp.Views/1.68.2/SkiaSharp.Views.iOS.md
- changelogs/SkiaSharp.Views/1.68.2/SkiaSharp.Views.tvOS.md
- changelogs/SkiaSharp/1.68.1/SkiaSharp.humanreadable.md
- changelogs/SkiaSharp/1.68.2/SkiaSharp.humanreadable.md
- changelogs/SkiaSharp/1.68.2/SkiaSharp.md
- scripts/azure-templates-bootstrapper.yml
A working PR to update the docs
**Bugs Fixed**
None.
None.
None.
> Update docs for release

- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
- scripts/install-tizen.ps1
Update to the new Tizen:
- version 3.7
- java is included
- maybe Windows/macOS works now?
**Bugs Fixed**
None.
None.
None.
> Update to the new Tizen

- binding/Binding/EnumMappings.cs
- tests/Tests/EnumMappingsTest.cs
- tests/Tests/GRContextTest.cs
- tests/Tests/SKTest.cs
Adding back the removed enum members.
**Bugs Fixed**
None.
Removed the breaking changes,
None.
> Adding back the removed enum members

- VERSIONS.txt
- scripts/azure-pipelines.yml
> Update the version to 1.68.3

- cake/native-shared.cake
- native/linuxnodeps/build.cake
- native/nanoserver/build.cake
Allow the path to gn and ninja to be specified.
> Allow the path to gn and ninja to be specified

- scripts/azure-templates-variables.yml
> Improve the CI build label

- binding/Binding/SKShader.cs
Instead of adding a new overload that is already gone, add the new one that was added and is staying around for a bit.
**Bugs Fixed**
- None.
Removed new-obsolete member.
None.
> Use the correct shaders

- binding/Binding/SKPaint.cs
- binding/Binding/SkiaApi.generated.cs
- tests/Tests/SKColorFTest.cs
Expose `SKPaint.ColorF`
**Bugs Fixed**
- Fixes #1239
> Expose SKPaint.ColorF

- binding/Binding/SKPath.cs
- binding/Binding/SkiaApi.generated.cs
- tests/Tests/SKPathTest.cs
Expose SKPath.ToWinding
**Bugs Fixed**
- Fixes #840
> Expose SKPath.ToWinding

- cake/samples.cake
Do not add the SkiaSharp prefix to dependencies
> Do not add the SkiaSharp prefix to dependencies

- binding/Binding/SKColorSpaceStructs.cs
- changelogs/SkiaSharp.Vulkan.SharpVk/2.80.0/SkiaSharp.Vulkan.SharpVk.md
- changelogs/SkiaSharp/2.80.0/SkiaSharp.md
- source/SkiaSharp.Vulkan/SkiaSharp.Vulkan.SharpVk/GRVkExtensionsSharpVkExtensions.cs
- utils/SkiaSharpGenerator/ConfigJson/TypeMapping.cs
- utils/SkiaSharpGenerator/Generate/Generator.cs
Cleaned up the APIs that introduced new usages of `SKMatrix44`. That type is a bit bad and is going away very soon.
Also tweaked the name of the extensions class to avoid any conflicts with other extension classes.
> Some review tweaks

- .gitignore
- build.cake
- cake/UtilsManaged.cake
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
- tests/SkiaSharp.NetCore.Tests/SkiaSharp.NetCore.Tests.csproj
- tests/SkiaSharp.Vulkan.NetCore.Tests/SkiaSharp.Vulkan.NetCore.Tests.csproj
Add code coverage to the tests
> Add code coverage to the tests

- binding/Binding/GRContext.cs
- binding/Binding/SKImageFilter.cs
- binding/Binding/SkiaApi.generated.cs
Reduce the usage of deprecated functions in the native engine.
Also waiting on a response for https://groups.google.com/g/skia-discuss/c/yET12qxjG18
**Bugs Fixed**
- Relates to #1334
> Reduce the usage of deprecated native functions

- binding/Binding/SKFontStyleSet.cs
It appears that sometimes the unit tests fail with this type... Not sure exactly why, but will be good to test this.
> Keep the font set alive

- binding/Binding/SKTextBlob.cs
Related to #1362 
Not sure if this is the real issue... But can't hurt.
> Try keep the text blob builder alive

- scripts/Docker/wasm/Dockerfile
- scripts/azure-pipelines.yml
Seems the build is now failing because of missing files... Maybe the emscripten repo change too much for its own scripts?
> Clone a specific branch of WASM

- VERSIONS.txt
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
Increase the package versions for any new changes.
> Set the version to 2.80.1

- cake/shared.cake
- native/linux/build.cake
- scripts/azure-templates-bootstrapper.yml
- scripts/azure-templates-linux-matrix.yml
Fix the checks for dependencies and not use fontconfig
**Bugs Fixed**
- Fixes #1341
None.
None.
> Alpine appears to not be ignoring the request to build without fontconfig

- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKCanvasViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKGLViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.GTK/SKCanvasViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.GTK/SKGLViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SKCanvasViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SKGLViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Tizen/SKCanvasViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Tizen/SKGLViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKCanvasViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKGLViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.WPF/SKCanvasViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.WPF/SKGLViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKCanvasViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKGLViewRenderer.cs
- source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms/SKGLViewRenderer.cs
Switch from `Activator` to a constructor.
**Bugs Fixed**
- Fixes #1423
None.
Faster?
> Some performance improvements for Forms

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
Describe your changes here. 
**Bugs Fixed**
Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.
Added: 
Changed:
> Update GitHub Templates

- binding/Binding/SKMatrix.cs
- samples/Gallery/Uno/SkiaSharpSample.Shared/MainPage.xaml
Add a replacement method for the obsolete method.
**Bugs Fixed**
- Fixes #1415
Added: 
```csharp
struct SKMatrix {
public static SKMatrix CreateScaleTranslation (float sx, float sy, float tx, float ty);
}
```
None.
> Add a replacement method

- tests/Tests/SKPaintTest.cs
Handle invalid text correctly
**Bugs Fixed**
- Fixes #1432
> Handle invalid text correctly

- scripts/azure-templates-bootstrapper.yml
- tests/Tests/SKImageTest.cs
Seems there is some weird error with the image subset and encode logic. Fails randomly on CI. Who knows what is the real issue.
**Bugs Fixed**
- Related to #465 
> Fix the shaky unit test

- binding/HarfBuzzSharp.Android/nuget/build/monoandroid1.0/HarfBuzzSharp.targets
- binding/HarfBuzzSharp.Tizen/nuget/build/tizen40/HarfBuzzSharp.targets
- binding/HarfBuzzSharp.iOS/nuget/build/xamarinios1.0/HarfBuzzSharp.targets
- binding/HarfBuzzSharp.tvOS/nuget/build/xamarintvos1.0/HarfBuzzSharp.targets
- binding/HarfBuzzSharp.watchOS/nuget/build/xamarinwatchos1.0/HarfBuzzSharp.targets
- binding/SkiaSharp.Android/nuget/build/monoandroid1.0/SkiaSharp.targets
- binding/SkiaSharp.Tizen/nuget/build/tizen40/SkiaSharp.targets
- binding/SkiaSharp.iOS/nuget/build/xamarinios1.0/SkiaSharp.targets
- binding/SkiaSharp.tvOS/nuget/build/xamarintvos1.0/SkiaSharp.targets
- binding/SkiaSharp.watchOS/nuget/build/xamarinwatchos1.0/SkiaSharp.targets
- binding/SkiaSharp/nuget/build/wasm/SkiaSharp.props
- nuget/HarfbuzzSharp.nuspec
- nuget/SkiaSharp.NativeAssets.WebAssembly.nuspec
- nuget/SkiaSharp.Views.Uno.nuspec
- nuget/SkiaSharp.nuspec
- scripts/azure-templates-bootstrapper.yml
Use buildTransitive as well as build to ensure the native libraries reach the final app.
**Bugs Fixed**
- Fixes #1393
> Use buildTransitive as well as build

- binding/Binding/GRContext.cs
- binding/Binding/SKGraphics.cs
- binding/Binding/SkiaApi.generated.cs
- source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLLayer.cs
- tests/Tests/SKGraphicsTest.cs
- utils/SkiaSharpGenerator/BaseTool.cs
Add a few more GPU debugging and cleanup members.
**Bugs Fixed**
- Related to issue #1473 
> Add a few more GPU debugging members

- VERSIONS.txt
- scripts/azure-pipelines.yml
Update the version to 2.80.3
**Bugs Fixed**
None.
None.
None.
> Update the version to 2.80.3

- VERSIONS.txt
- build.cake
Register the new HarfBuzzSharp WASM package. This should have been in the other PR.
**Bugs Fixed**
- Related to #1447
> Register the new HarfBuzzSharp WASM package

- utils/WasmTestRunner/WasmTestRunner.csproj
> Update the ChromeDriver

- source/SignList.xml
Load the fonts on iOS.
**Bugs Fixed**
- Fixes #1504
> Load the fonts on iOS

- scripts/azure-pipelines.yml
- scripts/install-tizen.ps1
With the update, make sure to upgrade the older LLVM to the latest available.
**Bugs Fixed**
None.
None.
None.
> Update to a later Tizen Studio

- SignList.xml
- build.cake
- cake/msbuild.cake
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
> Use v2 Signing

- native/wasm/build.cake
- tests/SkiaSharp.Wasm.Tests/SkiaSharp.Wasm.Tests.csproj
- tests/SkiaSharp.Wasm.Tests/Tests.cs
- utils/WasmTestRunner/WasmTestRunner.csproj
> Add a picture test to the WASM tests

- scripts/Docker/ubuntu16/clang-cross/build-local.sh
- utils/NativeLibraryMiniTest/docker/build.sh
- utils/NativeLibraryMiniTest/docker/nuget.config
Making things easier to build and test locally.
**Bugs Fixed**
> Improve the local builds

- samples/Basic/Docker/Console/nuget.config
- samples/Basic/Docker/WebApi/nuget.config
> Make things consistent

- README.md
Add readme mentions for SkiaSharp.Views.Uno.
> docs: Add unoplatform references

- binding/Binding/SKData.cs
- binding/Binding/Util.cs
- tests/Tests/SKCanvasTest.cs
- tests/Tests/SKTest.cs
Just some new things.
**Bugs Fixed**
> Add a few APIs that make things better later

- samples/Basic/Desktop/SkiaSharpSample/SkiaSharpSample.csproj
- samples/Basic/Gtk/SkiaSharpSample/SkiaSharpSample.csproj
- samples/Basic/WPF/SkiaSharpSample/SkiaSharpSample.csproj
- samples/Basic/Xamarin.Forms/SkiaSharpSample.GTK/SkiaSharpSample.GTK.csproj
- samples/Basic/Xamarin.Forms/SkiaSharpSample.WPF/SkiaSharpSample.WPF.csproj
- samples/Gallery/Desktop/SkiaSharpSample/SkiaSharpSample.csproj
- samples/Gallery/WPF/SkiaSharpSample/SkiaSharpSample.csproj
- samples/Gallery/Xamarin.Forms/WPF/WPF.csproj
- source/SkiaSharp.Build.targets
- source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Android/SKXamlCanvas.Android.cs
- source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Android/SkiaSharp.Views.Uno.Android.csproj
- source/SkiaSharp.Views/SkiaSharp.Views.Android/SKCanvasView.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Android/SKLockedSurface.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Android/SKSurfaceView.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Android/SurfaceFactory.cs
- source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKCanvasView.cs
* Improve code reuse among all the raster views on Android
* Updated samples to use net472
**Bugs Fixed**
> Refactor the Android surface factory

- build.cake
- cake/UpdateDocs.cake
- cake/UtilsManaged.cake
- cake/externals.cake
- cake/msbuild.cake
- nuget/_NativeAssets.nuspec
- nuget/_NuGets.nuspec
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
> Split the packages up for better downloads

- build.cake
- nuget/_NativeAssets.nuspec
- scripts/azure-pipelines.yml
- tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.csproj
- Make sure to pack _everything_, not just the stuff in folders
- Pin the version of xharness for now until we can get a good install of net6 that doesn't break other things.
**Bugs Fixed**
- Fixes #1682 
> Pack things correctly and pin the xharness version

- scripts/azure-pipelines.yml
Adds support for newer emscripten builds.
**Bugs Fixed**
None
None
None
> [Wasm] Add support for emscripten 2.0.23

- binding/HarfBuzzSharp.UWP/HarfBuzzSharp.UWP.csproj
- binding/SkiaSharp.UWP/SkiaSharp.UWP.csproj
- build.cake
- nuget/HarfbuzzSharp.nuspec
- nuget/SkiaSharp.HarfBuzz.nuspec
- nuget/SkiaSharp.Views.Desktop.Common.nuspec
- nuget/SkiaSharp.Views.Forms.GTK.nuspec
- nuget/SkiaSharp.Views.Forms.WPF.nuspec
- nuget/SkiaSharp.Views.Forms.nuspec
- nuget/SkiaSharp.Views.Gtk2.nuspec
- nuget/SkiaSharp.Views.Gtk3.nuspec
- nuget/SkiaSharp.Views.Maui.Controls.Compatibility.nuspec
- nuget/SkiaSharp.Views.Maui.Controls.nuspec
- nuget/SkiaSharp.Views.Maui.Core.nuspec
- nuget/SkiaSharp.Views.Uno.nuspec
- nuget/SkiaSharp.Views.WPF.nuspec
- nuget/SkiaSharp.Views.WinUI.nuspec
- nuget/SkiaSharp.Views.WindowsForms.nuspec
- nuget/SkiaSharp.Views.nuspec
- nuget/SkiaSharp.Vulkan.SharpVk.nuspec
- nuget/SkiaSharp.nuspec
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
- source/SkiaSharp.Build.props
- source/SkiaSharp.Build.targets
- source/SkiaSharp.Views/SkiaSharp.Views.UWP/SkiaSharp.Views.UWP.csproj
Add the .pdb files to the packages. This is just the managed parts as the native ones are huge (50MB per Windows arch)
**Bugs Fixed**
- missing symbols
None.
> Add main PDB files to the packages

- build.cake
- cake/UpdateDocs.cake
- cake/msbuild.cake
- cake/xharness-android.cake
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
- scripts/install-vs.ps1
Seems all the copies of the native libraries are over 5GB and CI does not like that :)
**Bugs Fixed**
> Reduce the size of the artifacts

- samples/Basic/Maui/SkiaSharpSample/SkiaSharpSample.csproj
> Update MAUI sample

- samples/Basic/Maui/SkiaSharpSample/Platforms/Android/AndroidManifest.xml
- samples/Basic/Maui/SkiaSharpSample/Platforms/Windows/Package.appxmanifest
- samples/Basic/Maui/SkiaSharpSample/SkiaSharpSample.csproj
- scripts/azure-pipelines.yml
- source/SkiaSharp.Build.props
- source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Core/Extensions.cs
P14 had a few extra breaks just now 😄
> Update Maui to the later P14

- build.cake
- nuget/SkiaSharp.Views.WinUI.nuspec
- scripts/azure-pipelines.yml
Since WinUI is stable, the things on top of it can also be stable
> Build stable of everything

- scripts/azure-pipelines-complete.yml
- scripts/azure-templates-provisioning-profiles.yml
- scripts/azure-templates-stages.yml
Try using the shared certificates.
> Use macOS 11 to get things green

- source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SKSwapChainPanel.Wasm.cs
- source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SKXamlCanvas.Wasm.cs
- source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Wasm/SkiaSharp.Views.Uno.WinUI.Wasm.csproj
- source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Wasm/WasmScripts/SkiaSharp.Views.Uno.Wasm.js
Includes missing javascript support file for Uno.WinUI WebAssembly.
None.
> fix(unowasm): Adds missing Uno.WinUI javascript support file

- .gitignore
- benchmarks/SkiaSharp.Benchmarks/Benchmarks/Benchmarks.cs
- benchmarks/SkiaSharp.Benchmarks/Program.cs
- benchmarks/SkiaSharp.Benchmarks/SkiaSharp.Benchmarks.csproj
- benchmarks/SkiaSharp.Benchmarks/SkiaSharp.Benchmarks.sln
- benchmarks/SkiaSharp.Benchmarks/Utils/NonSeekableReadOnlyStream.cs
- binding/SkiaSharp.Skottie/Properties/SkiaSharpSkottieAssemblyInfo.cs
- source/SkiaSharp.Build.props
Just updates the things a bit.
> Update benchmark projects

- nuget/SkiaSharp.Skottie.nuspec
**Bugs Fixed**
- Fixes #
None.
None.
None.
> chore Remove docs files for skottie

- .gitignore
add IntelliJ .idea directory to git ignore
> add /.idea to git ignore

- .gitignore
- binding/Binding/SkiaApi.generated.cs
**Bugs Fixed**
- Fixes #
None.
None.
https://github.com/mono/skia/pull/92
> expose AVIF image encode format

- scripts/Docker/alpine/amd64/Dockerfile
Update the pretty old dependencies: libexpat edition.
**Bugs Fixed**
- Related to #718
- Related to #2009
None.
None.
None.
> Update libexpat to 2.4.8

- scripts/azure-pipelines-complete.yml
- scripts/azure-pipelines-tests.yml
- scripts/azure-pipelines-variables.yml
- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
- scripts/install-mono.sh
Update the Linux host machines as the older Ubuntu images are out of support.
> Update to ubuntu-20.04

- VERSIONS.txt
- build.cake
- source/SkiaSharp.Views/SkiaSharp.Views.Desktop.Common/SkiaSharp.Views.Desktop.Common.csproj
Just a general change to update things because we should.
> Use the latest versions of some NuGets and SDKs

- scripts/azure-pipelines-variables.yml
> Enable CodeQL

- VERSIONS.txt
- build.cake
- scripts/azure-pipelines-complete.yml
- scripts/azure-pipelines-variables.yml
- scripts/install-gtk.ps1
- source/Common/NullableAttributes.generated.cs
- source/SkiaSharp.Build.props
- source/SkiaSharp.Build.targets
- source/SkiaSharp.Views/SkiaSharp.Views.Desktop.Common/SkiaSharp.Views.Desktop.Common.csproj
- tests/SkiaSharp.Android.Tests/SkiaSharp.Android.Tests.csproj
- tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.csproj
- tests/SkiaSharp.NetCore.Tests/SkiaSharp.NetCore.Tests.csproj
- tests/SkiaSharp.Vulkan.Desktop.Tests/SkiaSharp.Vulkan.Desktop.Tests.csproj
- tests/SkiaSharp.Vulkan.NetCore.Tests/SkiaSharp.Vulkan.NetCore.Tests.csproj
- tests/SkiaSharp.Wasm.Tests/SkiaSharp.Wasm.Tests.csproj
- tests/SkiaSharp.iOS.Tests/SkiaSharp.iOS.Tests.csproj
- tests/Tests/SKColorFTest.cs
- tests/Tests/SKColorTest.cs
- tests/Tests/SKFontTest.cs
- tests/Tests/SKMatrix44Tests.cs
- tests/Tests/SKMatrixTests.cs
- tests/Tests/SKPaintTest.cs
- tests/Tests/SKPathTest.cs
> Update some more NuGets

- source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Mac/SKXamlCanvas.macOS.cs
#2398 had an issue but was merged in the hopes CI would work. I am now working on CI and this is blocking.
Fix for a2cfbb271568e5cedf22e07993dc9c0a04767c4f
> Use the correct method for setting Opaque on macOS

- scripts/azure-pipelines-complete-internal.yml
This PR just copies the complete template, but make sure it is manual and has access to internal templates.
This is not meant for any actual use, just to speed up testing builds because the internal devops has more agents.
> Add a manual, full-run pipeline

- scripts/azure-templates-download-artifacts.yml
- scripts/azure-templates-stages.yml
This may fix the issues when downloading artifacts from unix machines in forks.
Context: https://github.com/microsoft/azure-pipelines-tasks/issues/16526
> Use the new DownloadBuildArtifacts task

- VERSIONS.txt
- binding/Directory.Build.targets
- samples/Basic/UWP/SkiaSharpSample/SkiaSharpSample.csproj
- samples/Basic/Uno/SkiaSharpSample.UWP/SkiaSharpSample.UWP.csproj
- samples/Basic/Xamarin.Forms/SkiaSharpSample.UWP/SkiaSharpSample.UWP.csproj
- samples/Gallery/UWP/SkiaSharpSample/SkiaSharpSample.csproj
- samples/Gallery/Uno/SkiaSharpSample.UWP/SkiaSharpSample.UWP.csproj
- samples/Gallery/Xamarin.Forms/UWP/UWP.csproj
- scripts/azure-templates-bootstrapper.yml
- scripts/azure-templates-stages.yml
- tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.csproj
- tests/SkiaSharp.NetCore.Tests/SkiaSharp.NetCore.Tests.csproj
- tests/SkiaSharp.Vulkan.Desktop.Tests/SkiaSharp.Vulkan.Desktop.Tests.csproj
- tests/SkiaSharp.Vulkan.NetCore.Tests/SkiaSharp.Vulkan.NetCore.Tests.csproj
- tests/SkiaSharp.iOS.Tests/SkiaSharp.iOS.Tests.csproj
- utils/WasmTestRunner/Program.cs
- utils/WasmTestRunner/WasmTestRunner.csproj
Some of the tests/samples dependencies are quite old so we can update them.
> Update a few dependencies

- .config/dotnet-tools.json
- cake/UpdateDocs.cake
Just use the latest for some new APIs.
> Update Cake to the latest 2.x version

- nuget/HarfBuzzSharp.NativeAssets.iOS.nuspec
- nuget/SkiaSharp.NativeAssets.iOS.nuspec
I forgot to update the .nuspec files with the new artifacts...
> Pack the iossimulator RID artifacts

- binding/SkiaSharp/SKRunBuffer.cs
- binding/SkiaSharp/SKTextBlob.cs
- tests/Tests/SkiaSharp/SKTextBlobTest.cs
This was removed as it is not correct in its current form. But this PR adds back the feature in the correct form.
> Adding back text-based blobs

- source/SkiaSharp.Build.props
Make sure we detect the workloads for the preview better. Try new/more locations.
This is not perfect as the DOTNET_ROOT is no longer used, so we should do PATH scanning and then locate things, but this is too complex for the props. This is just for typical installs.
> Try do a better job at detecting workloads

- source/SkiaSharp.Build.props
I seem to have had a typo in my props...
> Fix the erroneous `>`

- changelogs/SkiaSharp.HarfBuzz/3.0.0/SkiaSharp.HarfBuzz.md
- changelogs/SkiaSharp.SceneGraph/3.0.0/SkiaSharp.SceneGraph.md
- changelogs/SkiaSharp.Skottie/3.0.0/SkiaSharp.Skottie.md
- changelogs/SkiaSharp.Views.Blazor/3.0.0/SkiaSharp.Views.Blazor.md
- changelogs/SkiaSharp.Views.Desktop.Common/3.0.0/SkiaSharp.Views.Desktop.Common.breaking.md
- changelogs/SkiaSharp.Views.Desktop.Common/3.0.0/SkiaSharp.Views.Desktop.Common.md
- changelogs/SkiaSharp.Views.Gtk3/3.0.0/SkiaSharp.Views.Gtk3.md
- changelogs/SkiaSharp.Views.Maui.Controls/3.0.0/SkiaSharp.Views.Maui.Controls.md
- changelogs/SkiaSharp.Views.Maui.Core/3.0.0/SkiaSharp.Views.Maui.Core.md
- changelogs/SkiaSharp.Views.Uno.WinUI/3.0.0/SkiaSharp.Views.Windows.breaking.md
- changelogs/SkiaSharp.Views.Uno.WinUI/3.0.0/SkiaSharp.Views.Windows.md
- changelogs/SkiaSharp.Views.WPF/3.0.0/SkiaSharp.Views.WPF.md
- changelogs/SkiaSharp.Views.WinUI/3.0.0/SkiaSharp.Views.Windows.breaking.md
- changelogs/SkiaSharp.Views.WinUI/3.0.0/SkiaSharp.Views.Windows.md
- changelogs/SkiaSharp.Views.WindowsForms/3.0.0/SkiaSharp.Views.WindowsForms.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.Android.breaking.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.Android.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.Mac.breaking.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.Mac.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.Tizen.breaking.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.Tizen.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.iOS.breaking.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.iOS.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.tvOS.breaking.md
- changelogs/SkiaSharp.Views/3.0.0/SkiaSharp.Views.tvOS.md
- changelogs/SkiaSharp.Vulkan.SharpVk/3.0.0/SkiaSharp.Vulkan.SharpVk.md
- changelogs/SkiaSharp/3.0.0/SkiaSharp.breaking.md
- changelogs/SkiaSharp/3.0.0/SkiaSharp.md
- scripts/azure-templates-stages.yml
When building the packages, also publish the final changelogs for future perusal and/or use.
> Update and publish the changelogs

- changelogs/SkiaSharp/3.0.0/SkiaSharp.humanreadable.md
- changelogs/SkiaSharp/3.0.0/SkiaSharp.md
> Add a human-radable diff

- changelogs/SkiaSharp/3.0.0/SkiaSharp.humanreadable.md
> Include platform changes

- scripts/azure-pipelines-complete-internal.yml
- scripts/azure-templates-stages.yml
> Add the new APIScan to the pipeline

- scripts/azure-templates-stages.yml
The ful compliance takes a long time and nightly is frequent enough.
> Only run the full compliance nightly

- scripts/azure-pipelines-variables.yml
> SkiaSharp 3.0 is ready for a first public preview

- scripts/VERSIONS.txt
Update harfbuzz to the latest version.
**Bugs Fixed**
None.
None.
None.
https://github.com/mono/skia/pull/118
> Update harfbuzz to 8.3.0

- native/winui/ANGLE.cake
- scripts/azure-templates-bootstrapper.yml
ANGLE is really struggling to checkout, so try reduce the size.
> Reduce checkout size of submodules

- native/windows/build.cake
- native/windows/libHarfBuzzSharp/libHarfBuzzSharp.vcxproj
- scripts/azure-pipelines-variables.yml
- scripts/azure-pipelines.yml
- scripts/azure-templates-stages.yml
Update build for APIScan needs.
> Run APIScan after packaging on the packages

- native/winui/SkiaSharp.Views.WinUI.Native/SkiaSharp.Views.WinUI.Native/SkiaSharp.Views.WinUI.Native.vcxproj
> Add the Vulcanized compiler options

- binding/SkiaSharp/SKObject.cs
> Fix comment

- scripts/azure-templates-stages.yml
This is not totally required, but it will make the targets easier to write if they are consistent.
> Order the folder name parts

- scripts/azure-pipelines.yml
- scripts/azure-templates-bootstrapper.yml
> Fix 1ES Builds

- scripts/azure-templates-stages.yml
The scanning is sort of correct, but it can be better.
> Scan the correct things correctly

- scripts/install-openjdk.ps1
There are some sort of weird corruption issues on macOS
> Installing Java is troublesome, so avoid it

- scripts/azure-templates-bootstrapper.yml
- scripts/azure-templates-stages.yml
- scripts/cake/externals.cake
- utils/NativeLibraryMiniTest/docker/NativeLibraryMiniTest.csproj
- utils/SkiaSharpGenerator/Generate/GenerateCommand.cs
- utils/SkiaSharpGenerator/SkiaSharpGenerator.csproj
- utils/generate.ps1
Sometimes I forget, sometimes I am lazy and need to generate the files on my mac and I have not yet made it all work. CI can do it though. This helps make sure it is all good as well as make sure we catch ABI changes as well as when I am lazy and just want to download the files.
> Validate the generated interop files

- interactive/README.dib
**Bugs Fixed**
- Fixes #
None.
None.
None.
> fix typo in README.dib

- source/SkiaSharp.NuGet.props
Use the new expressions for the licenses. The license file is still in the nuget package.
**Bugs Fixed**
- Fixes #2867
None.
None.
None.
> Use the new license expressions

- binding/SkiaSharp/SKColorFilter.cs
Using new things for faster things.
> Add spans to the color filters

- tests/Tests/SkiaSharp/SKPictureTest.cs
Seems some platforms are not exactly matching.
> Make unit tests more reliable

- binding/SkiaSharp/SkiaApi.generated.cs
CI has graced us with the real output.
> Re-generate APIs

- scripts/azure-templates-bootstrapper.yml
Authenticate to avoid "too many requests" errors.
> Authenticate Docker

- scripts/azure-templates-merger.yml
- scripts/download-artifact.ps1
I was too eager to merge before.
> Fix the download artifacts script

- scripts/SignList.xml
- scripts/azure-pipelines.yml
- scripts/azure-templates-stages.yml
Use the new signing templates to sign the macOS dylib artifacts.
> Update the signing template

- native/winui-angle/build.cake
- native/winui/build.cake
- scripts/azure-templates-stages.yml
The public CI agents are now running out of space.
> Build ANGLE separately

- scripts/azure-templates-stages.yml
Make sure the native assets are published.
> Download the native artifacts for _NativeAssets

- .github/workflows/rebase.yml
> Create a rebase bot

- scripts/install-dotnet-workloads.ps1
> Install with diagnostic

- scripts/azure-templates-bootstrapper.yml
- scripts/azure-templates-stages.yml
- scripts/install-android-sdk.ps1
> Don't fail Mac Catalyst just so we can go green

- scripts/azure-templates-stages.yml
Builds binaries for emscripten 3.1.56 used by .NET 9
**Bugs Fixed**
None
None.
None.
None.
> feat: Add support for .NET 9

- externals/.gitignore
- native/.gitignore
> Ignore some files to aid switching branches

- scripts/azure-templates-bootstrapper.yml
This was always a bit weird as we still needed to bump the skia submodule anyway.
> The fancy logic stopped working long ago

- nuget/SkiaSharp.NativeAssets.WinUI.nuspec
Add symbols for the new binaries to the packages as well.
> Add symbols to the packages

- scripts/VERSIONS.txt
- scripts/azure-pipelines-variables.yml
> Bump the version of the packages to 3.118

- scripts/VERSIONS.txt
Bump the dependency so we can use a new version number.
> Update harfbuzz to 8.3.1

- scripts/azure-templates-bootstrapper.yml
This was a feature added to help with merging, but it does not really help and it fails with forks after the increased restrictions
> Skip the skia PR checkout

- binding/HarfBuzzSharp.NativeAssets.WebAssembly/buildTransitive/HarfBuzzSharp.targets
- binding/SkiaSharp.NativeAssets.WebAssembly/buildTransitive/SkiaSharp.targets
The fix for #3064 was moved in #3082, but it went to the wrong targets. This PR moves the fix from harfbuzz to skia.
> Move the WASM fix to SkiaSharp

- binding/HarfBuzzSharp.NativeAssets.Linux/HarfBuzzSharp.NativeAssets.Linux.csproj
- binding/SkiaSharp.NativeAssets.Linux/SkiaSharp.NativeAssets.Linux.csproj
The PackageFile is a typo and is the build action, not the attribute
> Use the correct PackagePath attribute

- scripts/azure-templates-bootstrapper.yml
Not sure why, but sometimes the run of dotnet cake just hangs and never actually starts. This hopefully will catch that and retry.
> The initial run of dotnet and/or cake hangs

- scripts/azure-templates-bootstrapper.yml
Restore the tools before using them.
> Restore the .NET tools first

- binding/IncludeNativeAssets.HarfBuzzSharp.targets
- binding/IncludeNativeAssets.SkiaSharp.targets
> Fix local targets for ARM machines

- binding/IncludeNativeAssets.HarfBuzzSharp.targets
- binding/IncludeNativeAssets.SkiaSharp.targets
Linux tests are failing in main.
**Bugs Fixed**
- Fixes regression from https://github.com/mono/SkiaSharp/pull/3190
None.
None.
None.
> fix linux tests

- scripts/azure-templates-merger.yml
- scripts/azure-templates-stages.yml
> The stageDependencies envvar is too big for devops

- scripts/Docker/debian/clang-cross/10/Dockerfile
- scripts/Docker/debian/clang-cross/12/Dockerfile
- scripts/Docker/debian/clang-cross/13/Dockerfile
The riscv64 binary for fontconfig-dev was updated from 2.15.0-2.1 to 2.15.0-2.2
> The fontconfig package was updated

- .github/workflows/label-with-ai.yml
> Use the new Triage assistant

- scripts/azure-pipelines-native.yml
Use the correct branch for the templates.
> Fix 1ES Templates

- .github/workflows/copilot-setup-steps.yml
> Add Copilot setup steps

- binding/SkiaSharp.Resources/ResourcesApi.generated.cs
- binding/SkiaSharp.SceneGraph/SceneGraphApi.generated.cs
- binding/SkiaSharp.Skottie/SkottieApi.generated.cs
- utils/SkiaSharpGenerator/BaseTool.cs
- utils/SkiaSharpGenerator/Generate/DocumentationStore.cs
- utils/SkiaSharpGenerator/Generate/GenerateCommand.cs
- utils/SkiaSharpGenerator/Generate/Generator.cs
- utils/SkiaSharpGenerator/Properties/launchSettings.json
- utils/generate.ps1
* Generator now preserves docs in generated files
* Generator now works on macOS
The macOS part is not super tested, but I was using Clang 17 from Xcode 26.
**Bugs Fixed**
- Related to #2348
> Improve the generator slightly

- scripts/extract-nupkg-files.ps1
> Add handling for symbol package suffix in folder name
