mono/SkiaSharp

README.md
Skia deps need to be actually downloaded before running `sync-and-gyp`
=> Fixed windows build instructions

binding/Binding/Binding.projitems, binding/Binding/SKCanvas.cs, binding/Binding/SKPaint.cs, binding/Binding/SkiaApi.cs, binding/Binding/Util.cs, binding/SkiaSharp.Windows.sln.DotSettings
Your current implementation ignores SkPaint's encoding, I've fixed that. I've also added IntPtr-based overloads, so optimizations like passing a pointer to the part of pinned `string` can be used.
=> IntPtr text manipulation overloads and encoding support

binding/Binding/SKObject.cs
Fix for random `NullReferenceException` described in issue #39
=> Fixed issue when exception would be thrown when property was null

.gitmodules, binding/Binding/Definitions.cs, binding/Binding/SKPath.cs, binding/Binding/SkiaApi.cs
Allows setting and getting the fill type in an SKPath. This is necessary, for example, to use the EvenOdd fill type. 
Note that changes to the skia C API were necessary also. You can see these changes in the petergolde/skia repo under the path-fill-type branch.
Edit:  Skia changes now in [PR 1][1] of mono/Skia
[1]: https://github.com/mono/skia/pull/1
=> Add setting/getting fill type to SKPath.

binding/Binding/SKPath.cs, binding/Binding/SkiaApi.cs
Added missing functions for SKPath:
- Reset()
- Rewind()
Added to SKPath.cs and SkiaAPI.cs in same style as SKPath.Close()
=> Added missing functions for SKPath

binding/Binding/SKTypeface.cs
I believe this is just a mistake on copy-n-paste the code. But CharsToGlyphs variant that accepts SKEncoding should use encoding instead of SKEncoding.Utf16.
=> CharsToGlyphs(SKEncoding) does not use the specified encoding.

binding/Binding/SKBitmap.cs, binding/Binding/SKCanvas.cs, binding/Binding/SKCodec.cs, binding/Binding/SKPath.cs, binding/Binding/SkiaApi.cs, docs/en/SkiaSharp/SKBitmap.xml, tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.csproj, tests/Tests/SKBitmapTest.cs, tests/Tests/SKCodecTest.cs
Adds a support for setting the ColorTable of a bitmap. Technically this is for index8 bitmaps, but I've left in the logic to check that to the actual Skia library.
Addresses #186.
Requires https://github.com/mono/skia/pull/36.
=> Add colortable setter support

binding/Binding/SKBitmap.cs
After looking at this there really isn't any reason that this check needs to be here.
=> remove index8 check for adding pixels

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKCanvasViewRenderer.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKGLViewRenderer.cs
By default, the UWP and Android views are not opaque. These patches explicitly change the iOS renderers to copy this behavior.
I split the patches in two because I think the GL one could have some performance impacts.
This would fix #198
=> Make the iOS Forms views non-opaque

source/SkiaSharp.Svg/SkiaSharp.Svg.Shared/SKSvg.cs
Reverts mono/SkiaSharp#239
Reverting as this does not really follow the SVG spec: http://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute
See the original issue for more info:  #239
=> Revert "SKSvg - Fixed SVG not loaded when viewport / viewbox not specified"

cake/BuildExternals.cake, native-builds/libSkiaSharp_linux/Makefile
I've managed to produce a portable Linux binary using Holy Build Box.
However, I had to use static version of libfreetype.
https://files.gitter.im/AvaloniaUI/Avalonia/xFjI/libSkiaSharp.so - portable binary file.
I'll upload my docker container and instructions soon. That should allow to produce a single build of libSkiaSharp for most of modern Linux distributions based on glibc. It should work on
-    Debian >= 7
-    Ubuntu >= 12.04
-    Red Hat Enterprise Linux >= 6
-    CentOS >= 6
And their derivatives. I had to use more recent fontconfig, so library won't work on CentOS 5 and Debian 6, but I'm not sure that Skia# needs to target those ancient distros.
=> Use static libfreetype for Linux

source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKXamlCanvas.cs
The ImageBrush used as background holds a reference to the WriteableBitmap
=> Fix for memory leak in UWP SKXamlCanvas 

binding/Binding/SKStream.cs, binding/Binding/SkiaApi.cs
Fixed issue #134, it looks like it is SkiaSharp bug after all.
This is a major issue now that [Telerik uses SkiaSharp](http://www.telerik.com/forums/could-not-aot-the-assembly-skiasharp-dll) for their Xamarin controls.
No quarantee the fix is 100% correct but passing SKData object directly to imported method seems wrong. Fixed version survives AOT just fine.
=> Fixed "Could not AOT the assembly" issue for Xamarin

binding/Binding/SKBitmap.cs
Decoded images will always be unpremul, but skia draws in premul.
This is a "fix" for #282. Not really a bug since we are preserving image data, but we will probably always have to use premul when drawing. So this change is rather an enhancement that a fix.
=> Always decode images with premultiplied alpha

source/SkiaSharp.Views/SkiaSharp.Views.Android/AndroidExtensions.cs
To calculate the total number of bytes for the bitmap, you must multiply HEIGHT by the number of bytes per row, not the width. If multiplied by the width, this can caused the copy to fail if the bitmaps height is greater than its width since not enough bytes will be copied.
=> Issue #333, corrected formula for total bitmap bytes

binding/Binding/SKBitmap.cs, binding/Binding/SKCodec.cs, binding/Binding/SKData.cs, binding/Binding/SKDocument.cs, binding/Binding/SKManagedStream.cs, binding/Binding/SKManagedWStream.cs, binding/Binding/SKObject.cs, binding/Binding/SKStream.cs, binding/Binding/SKTypeface.cs, source/SkiaSharpSource.Mac.sln, tests/Tests/SKManagedStreamTest.cs
This PR addresses #83 and #376
I believe there is a bug in the native skia that does not dispose properly of the streams passed to `SKTypeface`. As this was where I started working with streams (the loading of fonts) I had written code, that was flawed, to get around the issue. A problem arose when memory was tight or bitmaps were used - sometimes the GC would dispose the stream, when it should have waited for the native side to let it know when to destroy.
`SKManagedStream` is a special case in that it's lifetime is directly managed by the native, and the managed side needs to wait for the dispose event to be triggered from the native destructor. As a result, I keep a strong reference to the managed type to prevent them inadvertently disposing the native side when the GC kicks in.
As a …
=> SKManagedStream Memory Fixes

docs/en/SkiaSharp/SKMatrix.xml
I saw a typo in the documentation shown by intellisense. 
I guess this is the correct place to fix it?
Take care,
-Martin
=> fixed typo in SKMatrix.xml

docs/en/SkiaSharp/SKBitmap.xml, docs/en/SkiaSharp/SKSurface.xml
LockPixels() and UnlockPixels() have been removed in the latest SkiaSharp, but nearly all documentation about SKBitmap on the Internet still refers to them (as does the official SKBitmap.xml document itself). After wasting an hour this morning wondering what was going on (since I've never used Skia before), and researching why even simple examples wouldn't compile, I added a note to the SKBitmap documentation that explains that these are no longer required operations, per discussion at https://bugs.chromium.org/p/skia/issues/detail?id=6481&desc=2 .  I don't know if the "note" I added is really the *correct* update for the documentation, but I sure would've saved me a lot of time today if it had been included.  Feel free to alter its wording.
=> Update SKBitmap docs for removal of Lock/UnlockPixels

source/SkiaSharp.Views/SkiaSharp.Views.Android/GLTextureView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLTextureViewRenderer.cs
When the app is paused, the texture is destroyed. This is all good so far. 
However, when the app resumed, the texture is re-created under the hood and thus follows another path - and this is where I was missing logic to re-create the SkiaSharp context.
=> GH-460 : Make sure to re-create the SkiaSharp context

binding/Binding/SKBitmap.cs, binding/Binding/SkiaApi.cs, tests/Tests/SKBitmapTest.cs
The original `SkBitmap::copyTo` method was removed from the native code. In an effort to preserve backwards compatibility, that method was ported to the managed API, however it was not done properly (by me).
=> Properly copy bitmaps. Fixes #497

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKCanvasViewRendererBase.cs
Fixed OnTouch e.Location error if `IgnorePixelScaling = true;` in Android and Tizen
=> fix Android and Tizen Location error #581

binding/HarfBuzzSharp.Tizen/nuget/build/tizen40/HarfBuzzSharp.targets, binding/SkiaSharp.Tizen/nuget/build/tizen40/SkiaSharp.targets
Current temprary hacks for tizen-x86 RID are still needed because the Tizen 4.0 platform
including .NETCore 2.0 does not understand the tizen-x86 RID.
In this changes, Use TizenTPKFiles defined in Tizen.NET.Sdk instead of Link and CopyToOutputDirectory
to solve following problems.
- The linked file (runtime/linux-x86/native/foo.so) is displayed in VS Project tree.
- The linked file is always copied to tpkroot/bin even when RID is specified.
- The linked file can't be excluded with the file excluding features of Tizen.NET.Sdk.
The files added to TizenTPKFiles will be copied to tpkroot by Tizen.NET.Sdk, see
https://github.com/Samsung/build-task-tizen/blob/master/src/Tizen.NET.Build.Tasks/build/Tizen.NET.Sdk.Packaging.targets
=> Fix target files for Tizen to use TizenTPKFiles

build.cake, cake/BuildExternals.cake, native-builds/libHarfBuzzSharp_windows/libHarfBuzzSharp.vcxproj, scripts/pipeline.groovy
Statically Link Windows Binaries #136 and add support for feature branches
=> Statically Link Windows Binaries

scripts/pipeline.groovy
It's currently incompatible with the changes Jenkins is making as part of JEP-210: issues.jenkins-ci.org/browse/JENKINS-54680
=> Disable log compression in pipeline.groovy

README.md
I'm not sure if this is the wording you would prefer, but externals-windows fails with an unintuitive python exception if you don't have MSVC installed (e.g., a user with Visual Studio and only the .NET development pack) so I added it to the pre-reqs for running bootstrapper.
=> Add note about MSVC requirement

scripts/pipeline.groovy
Right now, the workspace is only cleared on success, making every failure clog the machine.
=> Make sure to always clean the workspace

cake/BuildExternals.cake, scripts/build-linux.sh, scripts/pipeline.groovy
There appears to be some major performance boosts with `clang` (#686), so I am trying out a build for that. And, I am going to drop the version of Ubuntu used for building to 14.04 for increased compatibility with older Linux distros.
> VS bug [#777658](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/777658)
=> Build Native Linux on Ubuntu 14 with Clang

cake/BuildExternals.cake, native-builds/libSkiaSharp_osx/libSkiaSharp.xcodeproj/project.pbxproj
Apple moved our cheese with macOS 10.7, so apps using SkiaSharp cannot run on 10.7.
This PR drops the minimum version and fixes #775.
This app was built with SkiaSharp targeting macOS 10.14 and a minimum of 10.7: [SkiaSharpSample.app.zip](https://github.com/mono/SkiaSharp/files/2867589/SkiaSharpSample.app.zip)
Here it is running on my machine (10.14):
> VS bug [#793482](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/793482)
=> Dropping the macOS minimum version to 10.7

.gitmodules, binding/Binding/SKMatrix.cs, binding/Binding/SKPaint.cs, binding/Binding/SkiaApi.cs
It's quite a bit faster to reuse `SKPaint` objects (due to the all pinvoke, extra bookkeeping for the references, etc.). But without having an reset method (https://skia.org/user/api/SkPaint_Reference#SkPaint_reset) it is hard to actually reuse objects, as it will be quite slow to reset properties one by one.
Native changes in: https://github.com/mono/skia/pull/59
Additionally I added a constructor to `SKMatrix` as it leads to better codegen, especially when inlining (like Avalonia conversion methods).
Benchmark code: https://gist.github.com/MarchingCube/3bcfbc8894a93b92cb2997b650a05508
Benchmark results for `SKPaint` reuse:
``` ini
BenchmarkDotNet=v0.11.4, OS=Windows 10.0.17763.316 (1809/October2018Update/Redstone5)
AMD Ryzen 7 2700X, 1 CPU, 16 logical and 8 physical cores
.NET Core …
```
=> Add Reset method to SKPaint and add constructor to SKMatrix

binding/Binding/SKRegion.cs
1. Cleaned up SKRegion file in terms of style. Style was inconsistent at best in this file.
* To assist with this in future, I have added `omnisharp.json` to the project root, which OmniSharp can utilize to format the C# source files automatically. Nobody should need to deal with repo style on a manual basis where possible.
* If this file doesn't quite meet every standard set in the style guide, please feel free to alter the rules laid out therein. I just want to make it as easy as possible for potential contributors to get it right the first time. 😊 
2. Added some constructors to SKRegion:
* `new SKRegion(SKRect rect)` -- creates a new region and calls `SetRect(rect)`
* `new SKRegion(SKPath path)` -- creates a new region and calls `SetPath(path)`
3. Altered `SetPath(SKPath path)` method …
=> SKRegion: Add constructors and methods for easier interaction with SKRectI and SKPath

README.md
Changed the API link to reflect the fact that it's now hosted on Microsoft Docs.
=> Changed the API link

README.md, build.cake, scripts/azure-pipelines.yml
This is useful for more specific labels besides just preview, we may want alpha/beta/rc.
=> Add support for a custom preview label

source/SkiaSharp.Views/SkiaSharp.Views.Android/SKCanvasView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Apple/SKCGSurfaceFactory.cs, source/SkiaSharp.Views/SkiaSharp.Views.Apple/SKCanvasLayer.cs, source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKCanvasView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Desktop/SKControl.cs, source/SkiaSharp.Views/SkiaSharp.Views.Gtk/SKWidget.cs, source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKCanvasView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKCanvasView.cs, source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKXamlCanvas.cs, source/SkiaSharp.Views/SkiaSharp.Views.WPF/SKElement.cs
In some cases, a view dimension may be < 1, thus the allocation for 0 bytes of memory is not actually possible.
Fixes #759
> VS bug [#770231](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770231), VS bug [#934149](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/934149)
=> None of the raster views should try allocate 0x0 memory. Fixes #759

.gitmodules, VERSIONS.txt, native-builds/libHarfBuzzSharp_android/config.h, native-builds/libHarfBuzzSharp_android/jni/Application.mk, native-builds/libHarfBuzzSharp_android/jni/HarfBuzzSharp.mk, native-builds/libHarfBuzzSharp_ios/config.h, native-builds/libHarfBuzzSharp_ios/libHarfBuzzSharp.xcodeproj/project.pbxproj, native-builds/libHarfBuzzSharp_linux/Makefile, native-builds/libHarfBuzzSharp_linux/config.h, native-builds/libHarfBuzzSharp_osx/config.h, native-builds/libHarfBuzzSharp_osx/libHarfBuzzSharp.xcodeproj/project.pbxproj, native-builds/libHarfBuzzSharp_tizen/config.h, native-builds/libHarfBuzzSharp_tizen/project_def.prop, native-builds/libHarfBuzzSharp_tvos/config.h, native-builds/libHarfBuzzSharp_tvos/libHarfBuzzSharp.xcodeproj/project.pbxproj, native-builds/libHarfBuzzSharp_uwp/config.h, native-builds/libHarfBuzzSharp_uwp/libHarfBuzzSharp.vcxproj, native-builds/libHarfBuzzSharp_watchos/config.h, native-builds/libHarfBuzzSharp_watchos/libHarfBuzzSharp.xcodeproj/project.pbxproj, native-builds/libHarfBuzzSharp_windows/config.h, native-builds/libHarfBuzzSharp_windows/libHarfBuzzSharp.vcxproj, samples/Gallery/Shared/SamplesManager.cs, samples/Gallery/Xamarin.Forms/Core/DetailContentsPage.xaml.cs, tests/SkiaSharp.NetCore.Tests/SkiaSharp.NetCore.Tests.csproj
- Windows [x] 
- Linux [x] 
- Tizen [x] 
- Android [x] 
- Mac [x] 
On Linux the compiler seems to have issues. Can we use clang to build HarfBuzz?
@mattleibow
=> Update HarfBuzz 2.5.2

scripts/azure-pipelines.yml
`PublishPipelineArtifact` does not allow for anonymous access, so use `PublishBuildArtifacts` instead to make `native-default` public.
=> Publicly publish all the native artifacts

cake/BuildExternals.cake
Changes the artifact name for the externals-download target from "native" to "native-default" to match the Azure Build.
This allows the [Build Preparation instructions](https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp#preparation-1) to work as documented instead of returning a 404 error.
**Bugs Fixed**
- Related to issue #889, #883 
- Fixes #883
**Changes**
Changes the artifact name from "native" to "native-default" to match the Azure Build Pipeline.
Also some minor refactoring of local string constants for the output path.
Since the unzipped folder is named "native-default", it is renamed back to "native" so the rest of the build scripts can still work.
- [ NA ] Has tests (if omitted, state reason in description) …
=> Change native artifact name to match Azure Build.

binding/HarfBuzzSharp.Desktop/nuget/build/net45/HarfBuzzSharp.targets, binding/SkiaSharp.Desktop/nuget/build/net45/SkiaSharp.targets
Add the libSkiaSharp.dylib to the app bundle when using the full framework
**Bugs Fixed**
- Fixes #913
None.
The libSkiaSharp.dylib and libHarfBuzzSharp.dylib should now be added to the app bundles for full framework mac apps.
=> Add the libSkiaSharp.dylib to the app bundle when using the full framework

cake/BuildExternals.cake
Build the new `arm64_32` architecture for watchOS.
**Bugs Fixed**
- Related to issue #961
None.
None.
=> Build arm64_32 architecture for watchOS

binding/Binding/SKRoundRect.cs, tests/Tests/SKRoundRectTest.cs
Resolves a memory leak when the transformation fails, the allocated round rect that should have been deleted.
**Bugs Fixed**
- Resolves #994
Added: 
- `public bool SKRoundRect.TryTransform (SKMatrix matrix, out SKRoundRect transformed)`
None public. Just no longer leaks an instance.
=> Fix a memory leak in SKRoundRect

binding/Binding/SKObject.cs, build.cake, cake/BuildExternals.cake, scripts/azure-templates-bootstrapper.yml, scripts/install-llvm.ps1, tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.csproj
Switch to using Clang 9 instead of MSVC for Win32 builds.
**Bugs Fixed**
- Resolves #758 
- Related to #686 
None.
There shouldn't be any visible _changes_ except for performance improvements. Google has been optimizing skia for Clang, and as a result the MSVC binaries are significantly slower. With this PR, we are using Clang on Windows desktop/Win32 so we get all those improvements now.
UWP is still using MSVC, but that will be changed at a later stage.
=> Use Clang for Windows (m68)

build.cake, cake/BuildExternals.cake, scripts/azure-templates-bootstrapper.yml, scripts/install-llvm.ps1
Describe your changes here. 
**Bugs Fixed**
- Related to #686
- Related to #1007
Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.
Added: 
Changed:
=> Use Clang for Windows (m79)

build.cake
Partial support for Vulkan backend, allowing to create GRContext, GrBackendRenderTarget and GrBackendTexture which can be used to render on/sampled from.
skia submodule changes refer to https://github.com/mono/skia/pull/60
=> Support for Vulkan context

nuget/SkiaSharp.Views.Forms.nuspec
Because the SkiaSharp.Views.Forms.WPF NuGet pulls in SkiaSharp.Views.Forms, we will get duplicate SkiaSharp.Views.Forms.dll files (1 from SkiaSharp.Views.Forms and one from SkiaSharp.Views.Forms.WPF).
This PR makes the SkiaSharp.Views.Forms version a reference assembly, and will never reach the app.
**Bugs Fixed**
- Fixes #1011
None.
The SkiaSharp.Views.Forms.dll is moved to the `ref` folder (from `lib`) in SkiaSharp.Views.Forms.nupkg
=> netstandard SkiaSharp.Views.Forms.dll should be ref-only

binding/HarfBuzzSharp.Desktop/nuget/build/net45/HarfBuzzSharp.targets, binding/SkiaSharp.Desktop/nuget/build/net45/SkiaSharp.targets
`dotnet build` is not quite the same as `msbuild` and `[System.Environment]::Is64BitOperatingSystem` cannot be used. We should use `[System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture` instead. Unfortunately, that type was added only in later MSBuilds based on net471+. 
However, `$(MSBuildRuntimeType)` was added in MSBuild 15 which is old enough.
**Bugs Fixed**
```
error MSB4185: The function "Is64BitOperatingSystem" on type "System.Environment" is not available for execution as an MSBuild property function.
```
None.
None. Except that it should now build net45+ with dotnet build.
=> Env.Is64BitOperatingSystem isn't in dotnet build

binding/Binding/SKBitmap.cs, binding/Binding/SKCanvas.cs, binding/Binding/SKColor.cs, binding/Binding/SKColorFilter.cs, binding/Binding/SKColorTable.cs, binding/Binding/SKImageFilter.cs, binding/Binding/SKPaint.cs, binding/Binding/SKPixmap.cs, binding/Binding/SKShader.cs, binding/Binding/SKVertices.cs, binding/Binding/SkiaApi.generated.cs, binding/libSkiaSharp.json, tests/Tests/SKColorTest.cs
Seems that when colors go into the native world and back, we aren't passing it correctly.
This issue keeps coming up when I update the native interop. I add tests that catch it, but it looks like every time I update, I do something to bypass the tests. I am writing bad tests then.
The reason for this time is because I switched to the new interop generator, but the rules for `SKColor` are special. When being passed INTO a method as arguments, then you can just pass `SKColor` (the struct) directly. But, as part of a RETURN, you have to use the actual `uint`. This is all because we are working with a nice struct on the managed side, but in the native side it is just a `uint`.
In this PR, I just switch to `uint` everywhere, except for arrays where I explicitly cast …
=> Fix bad colors

build.cake, scripts/azure-pipelines.yml, scripts/azure-templates-bootstrapper.yml
The PRs should use the format vX.X.X-pr.<pr-number>.<build-number>
**Bugs Fixed**
None
None.
None.
=> Use better PR labels for build artifacts

nuget/HarfbuzzSharp.NativeAssets.Linux.nuspec, nuget/HarfbuzzSharp.nuspec, nuget/SkiaSharp.NativeAssets.Linux.NoDependencies.nuspec, nuget/SkiaSharp.NativeAssets.Linux.nuspec, nuget/SkiaSharp.NativeAssets.NanoServer.nuspec, nuget/SkiaSharp.nuspec
Add the .targets file to the `buildTransitive` folder in the NuGet package. This only applies to net45 and Full Framework apps. This makes sure that the .targets file is always referenced and the native files are always copied as part of the build. 
The main issue this solves is for transitive dependencies with App -> Core -> ThirdParty -> SkiaSharp. In this scenario, the native libraries will only be copied as part of build for ThirdParty - which is not even part of the project. As a result, the app will never get the binaries. After this PR, each level will get the binaries, including the App and Core.
**Bugs Fixed**
- Fixes #1041
None.
The libSkiaSharp.* binaries will always be copied to the output folder for all projects …
=> Add the .targets file to buildTransitive

source/SkiaSharp.Views/SkiaSharp.Views.WindowsForms/SKGLControl.cs
Don't go straight for the max samples as the max may be 32 which may be too many for some GPUs
**Bugs Fixed**
- Fixes #1053
None.
`SKGLControl` now correctly respects the sample count of the control.
=> Don't go straight for the max samples

samples/Gallery/Shared/Samples/ThreeDSample.cs
In the 3D orthogonal rotation sample, the initial rotation matrix was set to 30 degrees around the Y-axis.  This is not necessary.  It suffices to set the initial rotation matrix to the identity matrix.
**Bugs Fixed**
None.
None
None
(not sure about this section)
=> suffices to start the rotation matrix as the identity matrix

samples/Gallery/Shared/SampleBase.cs, samples/Gallery/Shared/Samples/DecodeGifFramesSample.cs, samples/Gallery/Shared/Samples/ThreeDSample.cs, samples/Gallery/Shared/Samples/ThreeDSamplePerspective.cs
Removed an unused argument of type `TaskScheduler` from `AnimatedSampleBase`.
**Bugs Fixed**
None
None
None
(not sure about this section)
=> Remove an unused argument of type TaskScheduler from AnimatedSampleBase

nuget/SkiaSharp.Views.Desktop.Common.nuspec, nuget/SkiaSharp.Views.WPF.nuspec, source/SkiaSharp.Views/SkiaSharp.Views.WPF/SkiaSharp.Views.WPF.csproj
`SkiaSharp.View.WPF` now targets `.NET Core 3.0` in addition to `.NET Framework 4.5.1`.
**Bugs Fixed**
Related to issue #1029, which is about getting both `SkiaSharp.View.WPF` as well as `SkiaSharp.View.WindowsForms` to target `.Net Core`.
None
- NA
=> Multitarget Views.WPF

source/SkiaSharp.Views/SkiaSharp.Views.WPF/SkiaSharp.Views.WPF.csproj
In addition to having no compile-time dependency (and pointed out in https://github.com/mono/SkiaSharp/issues/1029#issuecomment-568156345), the nuspec file for View.WPF does not reference any OpenTK packages, so Views.WPF shouldn't need to reference these packages either.
**Bugs Fixed**
Related to issue #1029.  This change removes two warnings when targeting .NET Core in View.WPF.
None.
None.
- NA
=> Remove OpenTK references from View.WPF

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.WPF/SKTouchHandlerElement.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.WPF/SKTouchHandlerWinForms.cs
**Implement `SKTouchAction.WheelChanged` for WPF**
Add event handler for MouseWheel for both SKCanvasView and SKGLView Renderers
Added: 
- `void SKTouchHandlerElement.OnMouseWheel(object sender, MouseWheelEventArgs e);`
- `void SKTouchHandlerWinForms.OnMouseWheel(object** sender, MouseEventArgs e);`
Changed:
- `bool SKTouchHandlerElement.CommonHandler(object sender, SKTouchAction touchActionType, InputEventArgs evt);`
- `bool SKTouchHandlerWinForms.CommonHandler(object sender, SKTouchAction touchActionType, MouseEventArgs evt);`
Implement WPF backend
=> WPF Mouse Wheel on Touch Event

source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs
Construction of the `SKGLView` for macOS is not working as well as it used to.
**Bugs Fixed**
- Fixes some of #977
None.
Less issues on devices with limited/missing GL capabilities.
=> Fix some issues with macOS SKGLView

source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKSwapChainPanel.cs
Fix broken antialiasing with UWP SKSwapChainPanel.
**Bugs Fixed**
- Antialiasing is broken on GPU backend with UWP SKSwapChainPanel like #1053. Reproduced with NVIDIA GeForce GTX 970.
=> Fix broken antialiasing with UWP SKSwapChainPanel

binding/Binding/SKBitmap.cs, binding/Binding/SKColorF.cs, binding/Binding/SKImage.cs, binding/Binding/SKPicture.cs, binding/Binding/SKPixmap.cs, binding/Binding/SKShader.cs, binding/Binding/SkiaApi.generated.cs, binding/libSkiaSharp.json, tests/Tests/SKColorFTest.cs, tests/Tests/SKPixmapTest.cs, tests/Tests/SKShaderTest.cs, utils/SkiaSharpGenerator/Generate/Generator.cs
Adding the overloads that accept `SKColorF` and usually a `SKColorSpace`.
**Bugs Fixed**
- Fixes #1115
- Related https://github.com/mono/skia/pull/74
Added: 
- `class SKColorF`
New members.
=> Adding the SKColorF (with SKColorSpace) overloads

source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKXamlCanvas.cs
For some reason, some controls (such as the `ScrollViewer`'s `LeftHeader`, `TopHeader` and `TopLeftHeader`) are loaded twice.
We work around this by just adding a counter.
This will also fix any other controls that are a bit weird.
**Bugs Fixed**
- Fixes #1118
None.
Any code that relied on the `ScrollViewer`'s `LeftHeader`, `TopHeader` and `TopLeftHeader` loading twice and then unloading once will not work as expected. The control still loads twice, but the second (and subsequent) loads are ignored. Similarly, all unloads, except the load, will be ignore.
=> Prevent double load issue.

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SKGLViewRenderer.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKGLViewRenderer.cs
macOS and iOS draw immediately, so rather queue the redraw. Not only does this fix the stack overflow, but is now more consistent with the other platforms.
This also just fixes it for macOS and the render loop. Unlike iOS, macOS does not start the `CVDisplayLink` the same way as the `CADisplayLink`. As a result, the callback is on the background thread.
**Bugs Fixed**
- Fixes #1074
None.
This technically a breaking change for macOS in that the draw is now on the main thread. But, the loop never worked, and the one shot caused a stack overflow.
=> Queue the redraw for iOS and macOS

source/SkiaSharp.Views/SkiaSharp.Views.WindowsForms/SKGLControl.cs
If there are multiple `SKGLControls` drawing at the same time, there is the chance that one view may draw on another view. Or cause issues. This is because OpenGL is basically a thread-static library, and can only have a single "current" context per thread. By calling `MakeCurrent`, we are letting OpenGL know that _this_ view is drawing and all operations are here. The next view that wants to draw then also lets OpenGL know that it wants to do some work and the OpenGL can "shift" over to that one.
**Bugs Fixed**
- Fixes #920
None.
When multiple `SKGLControls` are created, there is some cross-talk. This PR makes sure that each view requests control over all operations.
=> Make sure the OpenGL context is "current" before drawing on it

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.WPF/SKTouchHandlerElement.cs
Make sure the view is still in the hierarchy
In the case of virtualized list views, the control may no longer be in screen, so we have to ignore touch events.
**Bugs Fixed**
- Fixes #978
None.
Bug fix.
=> Make sure the view is still in the hierarchy

binding/Binding/SKRunBuffer.cs, binding/Binding/SKTextBlob.cs, tests/Tests/SKTextBlobTest.cs
When the paint encoding is anything but GlyphId, the underlying allocation fails. This results in not only strange behaviour, but also invalid data. The run buffer is given a size, but nothing was allocated. This does 2 things:
- if a buffer is null, override the size
- if the encoding is not glyph, then change it temporarily
**Bugs Fixed**
- Fixes #1151
None.
Instead of throwing an unexpected exception when trying to USE the run buffer, the allocation will now succeed. And, if the each buffer on the run is null, then don't return a `Span<T>` that is not null.
=> Improve the experience with the SKTextBlobBuilder

cake/msbuild.cake, cake/native-shared.cake, cake/shared.cake, native/android/build.cake, native/android/libHarfBuzzSharp/jni/Application.mk, native/uwp/SkiaSharp.Views.Interop.UWP/SkiaSharp.Views.Interop.UWP.vcxproj, native/uwp/libHarfBuzzSharp/libHarfBuzzSharp.vcxproj, native/windows/libHarfBuzzSharp/libHarfBuzzSharp.vcxproj, scripts/azure-pipelines.yml, scripts/azure-templates-bootstrapper.yml, scripts/install-android-ndk.ps1, scripts/install-llvm.ps1, scripts/install-openjdk.ps1, scripts/install-tizen.ps1
Update all the build tools:
- Windows builds to use the v14.2 compilers
- Android to use the r19c (min Android API level 16)
- OpenJDK 13.0.2
- Tizen Studio 3.6
- Build on VS 2019
- Added build args to support preview/any VS installs
**Bugs Fixed**
None.
_I am secretly hoping that this will fix an issue that is preventing #1117 from building. I JUST set up a brand new machine and everything builds..._
None.
None.
=> Update all the build tools

binding/Binding/SKImageFilter.cs, tests/Tests/SKImageFilterTest.cs
**Description**
`SKImageFilter.CreateMerge` overloads now accept null for the image filter input argments
Since null  refers to the source graphics being drawn, passing null must be allowed. 
Added unit test
**Bugs Fixed**
`SKImageFilter.CreateMerge` doesn't throw `NullReferenceException` anymore.
- Related to issue #1163 
None.
`SKImageFilter.CreateMerge` doesn't throw `NullReferenceException` anymore.
- [y] Has tests (if omitted, state reason in description)
- [n] Rebased on top of master at time of PR
- [?] Changes adhere to coding standard
- [n] Updated documentation
=> Merge filter factory overloads now accept null arguments

binding/Binding/SKSurface.cs, source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLSurfaceViewRenderer.cs, source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLTextureViewRenderer.cs, source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLLayer.cs, source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLLayer.cs, source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Shared/SKPaintGLSurfaceEventArgs.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKGLSurfaceView.cs, source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKSwapChainPanel.cs, source/SkiaSharp.Views/SkiaSharp.Views.WindowsForms/SKGLControl.cs
In some instances, the managed canvas is being collected at the same time the new one is being created. This causes the the app to crash for some reason. The technically should not happen as the canvas is still valid - and we can see this when we set the canvas as a class field.
But, for now, just work around the issue by adding the canvas as a field.
In addition, do more granular construction of the GL objects, and then also reduce the amount of interop in the render loop.
**Bugs Fixed**
- Fixes #1121 
- Fixes #910
- Fixes #1173
- Fixes #1168
- Fixes #1144
None.
Some fixes for crashes.
=> Re-work views to avoid incorrect disposal

binding/Binding/SKTextBlob.cs, binding/Binding/SkiaApi.generated.cs
The `lang` parameter is not used, so remove it.
**Bugs Fixed**
- Fixes #1189
Internal only.
None.
=> Remove the `lang` parameter used by SKTextBlobBuilder

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs
Added motion event tool type to touch device type mappings
**Bugs Fixed**
- Fixes #1186
None
Touch events will now be the correct type: touch, pen, mouse.  Previously they were all touch.
=> Added device type to touch events (touch, mouse, pen)

source/SkiaSharp.Views/SkiaSharp.Views.UWP/AngleSwapChainPanel.cs, source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKSwapChainPanel.cs
Release the skia objects when the view is unloaded.
This was originally changed in 8039d0d0bbb135e8013be121cddf8716e7b8ce96 for the AngleSwapChainPanel view. But, this was not also extended to include the skia objects in SKSwapChainPanel.
Nothing needs to be re-created because it is all done in the first paint operation.
**Bugs Fixed**
- Fixes #1155
- Related to #705
None.
Draws correctly when unloaded and re loaded.
=> Release the skia objects when the view is unloaded

binding/Binding/SKColorSpace.cs, binding/Binding/SKData.cs, binding/Binding/SKFontManager.cs, binding/Binding/SKFontStyle.cs, binding/Binding/SKFontStyleSet.cs, binding/Binding/SKObject.cs, binding/Binding/SKTypeface.cs, tests/Tests/SKDataTest.cs, tests/Tests/SKFontManagerTest.cs, tests/Tests/SKFontStyleSetTest.cs, tests/Tests/SKShaperTest.cs, tests/Tests/SKTypefaceTest.cs
Make sure to not dispose system fonts.
`SKFontManager` and `SKTypeface` return a cached/singleton for system fonts. Do not dispose these because they may be in use in other parts of drawing code.
Because it is actually reference counted on the native side, we can allow the GC to collect it still. When the GC is working, this means that there are no more managed references and a disposal of the managed object will do nothing bad.
**Bugs Fixed**
- Fixes #1220
`SKFontManager.SKTypeface MatchFamily (string familyName);`
System fonts are no longer disposed.
=> Make sure to not dispose system fonts

source/SkiaSharp.Views/SkiaSharp.Views.Android/GLTextureView.cs
Make sure to request a redraw when the surface is created. This is not an issue when there is an update thread running.
**Bugs Fixed**
- Fixes #1232
None.
Fixes the issue 
=> [Android.Views] Refresh the surface when recreated

binding/Binding/SKPixmap.cs, binding/Binding/SkiaApi.generated.cs, tests/Tests/SKPixmapTest.cs
Expose a generic, writable span for the pixels. Also "cache" the info object in size so we don' have to hop the interop.
**Bugs Fixed**
- Fixes #1240
```csharp
class SKPixmap {
public unsafe Span<T> GetPixelSpan<T> () where T : unmanaged;
}
```
None.
=> Expose a generic, writable span for the pixels

binding/Binding/SKObject.cs
No need to allocate on disposal. The lazy property must not be used, but rather the field.
**Bugs Fixed**
None.
None.
None.
=> No need to allocate on disposal

source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKCanvasView.cs
Null out the field when disposing.
Not sure why iOS is drawing a disposed object, but just be safe.
**Bugs Fixed**
-  Fixes #960
None.
None visible... maybe fewer crashes?
=> Null out the field when disposing.

binding/Binding/SKImage.cs, binding/Binding/SKPixmap.cs, binding/Binding/SKSurface.cs, source/SkiaSharp.Views/SkiaSharp.Views.Android/AndroidExtensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.Apple/AppleExtensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.Gtk/GTKExtensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.Shared/Extensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.UWP/UWPExtensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.WPF/WPFExtensions.cs
Prevent the GC from collecting `this` and some cases where we no longer reference the object, just pixel data.
Reading pixels takes long enough that the GC will collect the object. Use GC.KeepAlive to prevent this.
Often the cause is that we go `SKImage` -> `SKPixmap`. This basically tells the GC that the bitmap is free, but in actual fact it is not - the pixmap is just a pointer to the pixel data.
**Bugs Fixed**
- Related to issue #1244
None.
Preserve `this`.
=> Prevent the GC from collecting "this" and "pixels"

VERSIONS.txt, build.cake, cake/UpdateDocs.cake, cake/msbuild.cake, scripts/azure-pipelines.yml, scripts/azure-templates-bootstrapper.yml, source/SkiaSharp.Build.targets
Ensure that the assemblies are in fact signed.
Since the addition of the `Xamarin.Build.TypeRedirector` NuGet package to fix up the VS2017 and VS2019 issues, the assembly is modified AFTER the signing, so that breaks it. This PR now specifies that the signing task depends on the redirection task.
Type redirector issues:
- https://github.com/xamarin/xamarin-macios/issues/5273
- https://github.com/xamarin/XamarinComponents/pull/764
**Bugs Fixed**
- Fixes #1267
None.
None.
=> Ensure that the assemblies are in fact signed

binding/Binding/SKFont.cs, binding/Binding/SKPaint.cs, binding/Binding/SKTypeface.cs, tests/Tests/SKFontTest.cs
Make `SKFont` glyph-only:
- hide the `SKFont` members that take strings/bytes
- hide the overloads that return arrays (promote the use of the "out span")
- expose string/byte members on `SKPaint`, and only expose the returning array (for consistency)
- use a single instance of `SKFont` for `SKTypeface` glyph members
The whole reason for this PR is to help define or direct type usage:
- `SKFont`  
- This type is very low level and just works with glyphs and unicode (`ushort` and `int`).
- To keep all the text members together, the other overloads are also defined, but are internal.
- For now, only the overloads that take an "outwards span" are exposed: `void Get(ReadOnlySpan<T> input, Span<T> output)`
- `SKPaint`  
- This type is for use with a canvas, so only …
=> Make the SKFont's public API glyph-only and the others types use it under the hood

binding/HarfBuzzSharp/HarfBuzzSharp.csproj, binding/SkiaSharp/SkiaSharp.csproj, cake/native-shared.cake, native/linuxnodeps/build.cake, nuget/HarfbuzzSharp.NativeAssets.Linux.nuspec, nuget/SkiaSharp.NativeAssets.Linux.NoDependencies.nuspec, nuget/SkiaSharp.NativeAssets.Linux.nuspec, scripts/Docker/alpine/amd64/Dockerfile, scripts/azure-pipelines.yml, scripts/azure-templates-bootstrapper.yml, utils/NativeLibraryMiniTest/Program.cs, utils/NativeLibraryMiniTest/build.sh
Adding a build for Alpine linux.
Builds on Alpine 3.9, tested all the way back to Alpine 3.7.
**Bugs Fixed**
- Related to #453
None.
The *.NativeAssets.Linux NuGet packages will now have an Alpine linux binary.
=> Add Alpine Native Libraries

binding/Binding/SKObject.cs, tests/Tests/SKObjectTest.cs
This PR fine tunes the disposal steps of a co-owned object pair. There are a few scenarios:
1. A managed creates and owns an underlying native instance. (`SKBitmap`)  
When the managed object is disposed, destroy the native object.
2. A native object creates a child native object that is managed on the native side. (`SKSurface` controls `SKCanvas`)  
When then the managed object destroys the native surface, the native canvas is also destroyed. There may be a case where a brand new native canvas is constructed in the same place - before the managed canvas is disposed. We have to make sure that e dispose the managed object before we destroy the native object.
3. A native object "creates" a managed object that is managed from the native side. (`SKSvgCanvas` controls …
=> Correctly dispose (again) the managed/native object relationship

binding/Binding/SKSurface.cs, binding/Binding/SkiaApi.generated.cs, tests/Tests/SKSurfaceTest.cs
Add an overload to `SKSurface.Snapshot()` that takes a bounds rect.
**Bugs Fixed**
- Related to issue #1334
=> Add snapshots with bounds

source/SkiaSharp.Build.targets
For some reason the `<Copy />` MSBuild task tries to copy files that it should have skipped due to it existing already. The `_CopyToOutputDirectoryDep` task is already using the correct inputs/outputs, but I suspect that using `AfterTargets` to control the steps is not correct and should be a `DependsOnTargets` for the build process.
However, since we are near release time, a simple retry might just be what it takes.
> This only happens on Windows because macOS and Linux do not support parallel builds.
=> [Build] Copy to output retries

samples/Gallery/WPF/SkiaSharpSample.sln
In the `samples\Gallery\WPF\SkiaSharpSample.sln` solution, I made the `SkiaSharpSample` project the default startup project by listing it first in the sln file.
None
No runtime changes.
This change improves the development experience.  When first cloning the repo or after deleting the `samples\Gallery\WPF\.vs` folder and then opening `samples\Gallery\WPF\SkiaSharpSample.sln` with Visual Studio, the default startup project will now be the `SkiaSharpSample` project.  This is an improvement because it is the only project that can be started.
- [NA] Updated documentation
=> SkiaSharpSample project now default startup project in the WPF SkiaSharpSample solution

binding/Binding/GRGlInterface.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/Interop/Evas.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKGLSurfaceView.cs
This actually "hides" an "issue" with the GL process. If we use the "default" APIs, then it explicitly requests a OpenGL ES 2.0 context. Then SkiaSharp will ask the API what version - which is actually 3.1 (at least on my watch), so then skia tries to set up a 3.x context, but only has the 2.x API.
We _could_ override/intercept the `glGetString(GL_VERSION)` call, but that is work. Also, we want new things. So, we first request a 3.x, then 2.x and _then_ get the default. Since 3.x came with Tizen 4.0+, we should _always_ be getting a 3.x context. Not only do we avoid this issue, but also get a newer context.
**Bugs Fixed**
- `SKGLView` crashes on the watch.
```csharp
public static GRGlInterface CreateEvas (IntPtr evas, IntPtr evasGlContext);
``` …
=> Explicitly request GL ES 3.x in case we have it

binding/Binding/SKTypeface.cs, binding/Binding/Util.cs, tests/Tests/SKFontTest.cs, tests/Tests/SKTypefaceTest.cs
Historically, SkTypeface.charsToGlyphs assumed the data was already in glyphs. So a UTF32 data array would pass the number of glyphs. Since that method was removed, we switched to SkFont.textToGlyphs. This worked in bytes. As a result, we need to make sure we convert from glyph count to byte count when we use it.
**Bugs Fixed**
- Fixes #1398
None.
`SKTypeface.GetGlyphs` now correctly passes the byte size to the font.
=> SKTypeface does not count bytes but glyphs

binding/Binding/SKSurface.cs
One overload of `SKSurface.Create` was not passing the `origin` parameter, it passed `BottomLeft` instead.
**Bugs Fixed**
- Related to issue #1401
None
The specific overload of `SKSurface.Create` behaves differently, but correctly now.
- [n] Has tests (if omitted, state reason in description)
- [y] Rebased on top of master at time of PR
- [y] Changes adhere to coding standard
- [n] Updated documentation
=> Fixed origin parameter is ignored in SKSurface.Create

binding/Binding/SKData.cs, tests/Tests/SKDataTest.cs
`SKData.Create(Stream)` throws when the stream is non-seekable. This is because we need the length before we can allocate memory. And, we can't get the length.
So, we create a copy of the stream, get the length and then allocate the memory. 
> It is a double copy, but that is unfortunately what we need to do.
**Bugs Fixed**
None.
None.
=> Fix issue when creating SKData from a non-seekable stream

binding/Binding/SKFont.cs
`SKFont.GetGlyphPath` (native code `SkFont::getPath`) can return `null`.
I didn't take that into account.
**Bugs Fixed**
- Related to issue #1408 
I still don't know why `DrawTextOnPath` fails on iOS, but the code should handle the `null` case anyway. Hard for me to debug without an iOS device.
None
`DrawTextOnPath` doesn't throw a `NullReferenceException` when `SKFont.GetGlyphPath` returns `null`
- [n] Has tests (if omitted, state reason in description)
- [y] Rebased on top of master at time of PR
- [y] Changes adhere to coding standard
- [n] Updated documentation
I wasn't able to write a unit test, because I couldn't find a single font for which `SKFont.GetGlyphPath` returns `null`.
However, I could …
=> SKCanvas.DrawTextOnPath can throw NullReferenceException

samples/Basic/Uno/SkiaSharpSample.Shared/MainPage.xaml, samples/Basic/Uno/SkiaSharpSample.Shared/MainPage.xaml.cs, samples/Gallery/Shared/Samples/CreatePdfSample.cs, samples/Gallery/Shared/Samples/CreateXpsSample.cs, samples/Gallery/Uno/SkiaSharpSample.Android/Properties/AndroidManifest.xml, samples/Gallery/Uno/SkiaSharpSample.Android/Resources/values/styles.xml, samples/Gallery/Uno/SkiaSharpSample.Shared/MainPage.xaml, samples/Gallery/Uno/SkiaSharpSample.Shared/MainPage.xaml.cs, scripts/azure-pipelines.yml, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Android/SKSwapChainPanel.Android.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Android/SkiaSharp.Views.Uno.Android.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Mac/SKSwapChainPanel.macOS.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Mac/SkiaSharp.Views.Uno.Mac.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SKSwapChainPanel.Wasm.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/WasmScripts/SkiaSharp.Views.Uno.Wasm.js, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.iOS/SKSwapChainPanel.iOS.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.iOS/SkiaSharp.Views.Uno.iOS.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno/SKSwapChainPanel.cs, source/SkiaSharp.Views/SkiaSharp.Views.Android/GLTextureView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLTextureView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLTextureViewRenderer.cs, source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Shared/GlesInterop/Gles.cs
Add the GPU views for the Uno Platform.
**Bugs Fixed**
- Related to #1420 , #1396 , #1396 , #1333
Adding `SKSwapChainPanel` to Uno Platform
New views.
=> Add the GPU views for Uno Platform

tests/Tests/SKImageTest.cs, tests/Tests/SKTest.cs
- Can't share encoded data if we have any modifiers
- Add some tests for this
**Bugs Fixed**
- Fixes #465 
=> Can't share encoded data if we have any modifiers

build.cake, cake/UpdateDocs.cake, cake/UtilsManaged.cake, cake/externals.cake, nuget/_NativeAssets.nuspec, nuget/_NuGets.nuspec, scripts/azure-templates-bootstrapper.yml
Create a NuGet containing just the native/nugets. This package can then be uploaded to the preview feed and downloaded by anyone.
The most common use case is the NuGets for generating docs or the native bits so that they don't have to built.
**Bugs Fixed**
=> Create a NuGet containing just the native/nugets

VERSIONS.txt, binding/Binding/SKFont.cs, binding/Binding/SkiaApi.generated.cs
Sometimes we can't return float, for some reason. There appears to be some bug or something on net472 + x86 + Marshal. It works in all other instances.
This is also very hard to test, because you need to be using VS and have the debugger attached... I blame the debugger for breaking things.
**Bugs Fixed**
- Fixes #1409
=> Sometimes we can't return float, for some reason

binding/Binding/SKMatrix.cs, tests/Tests/SKMatrixTests.cs
Revert the incorrect code for `SKMatrix.SetScaleTranslate`
**Bugs Fixed**
- Fixes #1451
=> Revert the code for SKMatrix.SetScaleTranslate

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SKGLViewRenderer.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Mac/SKSwapChainPanel.macOS.cs
Use NeedsDisplay instead of Display to prevent the double paint.
**Bugs Fixed**
- Fixes #1467
None.
No longer a double paint.
=> [macOS] Use NeedsDisplay instead of Display

VERSIONS.txt, binding/Binding/SKPicture.cs, binding/Binding/SkiaApi.generated.cs, tests/Tests/SKPictureTest.cs, tests/Tests/SKTest.cs
Add bindings for the serialization of SKPicture.
**Bugs Fixed**
- Fixes #880 
```csharp
class SKPicture {
public SKData Serialize ();
public void Serialize (Stream stream);
public void Serialize (SKWStream stream);
public static SKPicture Deserialize (IntPtr data, int length);
public static SKPicture Deserialize (ReadOnlySpan<byte> data);
public static SKPicture Deserialize (SKData data);
public static SKPicture Deserialize (Stream stream);
public static SKPicture Deserialize (SKStream stream);
}
```
New APIs that do not change behaviour of existing functionality.
=> Add bindings for the serialization of SKPicture

binding/Binding/GRGlInterface.cs
Allow to create Angle `GRGlInterface` from non UWP environment (WPF for an instance) from a new non deprecated `Create()` API. Another option will be making `AngleLoader` public to use a `CreateAngle (GRGlGetProcedureAddressDelegate get)`.
Now we are using a deprecated method, but I want to be sure that in the next releases we will be able to init Angle without reflection :) :
```C#
GrContext = GRContext.CreateGl(GRGlInterface.CreateNativeAngleInterface());
```
What I want:
```C#
GrContext = GRContext.CreateAngle();
```
basic `Create()` call will make an `openGL` `GRContext`.
=> Allow to create Angle GRGlInterface from non UWP environment

tests/Tests/SKMatrixTests.cs
Ensure that SKMatrix.IsInvertible does not crash.
**Bugs Fixed**
- Fixes #1526
=> Ensure that SKMatrix.IsInvertible does not crash

binding/HarfBuzzSharp/nuget/build/net462/HarfBuzzSharp.targets, binding/SkiaSharp/nuget/build/net462/SkiaSharp.targets
The older VS versions do not support the "everything as attributes" system, so go back to the older sub-element style. This is minimal effort to support older VS and more friendly neighborhood devs.
**Bugs Fixed**
- Fixes #1532 
None.
None.
=> Support VS 2013 because it is easy to do so

scripts/Docker/alpine/amd64/.dockerignore, scripts/Docker/alpine/amd64/build-local.sh
It appears that an updated gn is stricter when it comes to visibility. The upstream repo also has made this change.
Also, I have added a script to help builds locally.
**Bugs Fixed**
None.
None.
None.
=> Update externals for new gn and add helper script

binding/HarfBuzzSharp/nuget/build/wasm/HarfBuzzSharp.targets, binding/SkiaSharp/nuget/build/wasm/SkiaSharp.targets
WasmHead was only defined in projects from templates and is not reliable.
**Bugs Fixed**
Support for Uno 3.x recent templates.
None
None
=> fix: [Uno] Rely on build defined property to detect WebAssembly

source/SkiaSharp.Views/SkiaSharp.Views.WPF/SKElement.cs
Avoid NRE in SKElement when PresentationSource.FromVisual(this) returns null.
No tests as I do not know of a simple way to reproduce the underlying issue.
**Bugs Fixed**
- Fixes #1605
None
None
=> Make SKElement.OnRender do nothing if there is no PresentationSource

binding/Binding/GRBackendRenderTarget.cs, binding/Binding/GRBackendTexture.cs, binding/Binding/GRContext.cs, binding/Binding/GRDefinitions.cs, binding/Binding/GRMtlBackendContext.cs, binding/Binding/SkiaApi.generated.cs, binding/libSkiaSharp.json, source/SkiaSharp.Views/SkiaSharp.Views.Apple/SKMetalView.cs
* Use the shortened Mtl in the construcion type names because that is what we have done in the past :'(
* Use the longer Metal in the views layer :')
* Use GRMtlBackendContext as that is coming soon, so might as well get ahead
**Bugs Fixed**
=> Introduce some metal consistency

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SKGLViewRenderer.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKGLViewRenderer.cs
Be a bit more defensive in the display links because sometimes it might get into a case where one of the views are disposed.
**Bugs Fixed**
=> Be a bit more defensive in the display links

build.cake, scripts/azure-pipelines.yml, utils/WasmTestRunner/Program.cs
Every so often, the ChromeDriver goes out of date and requires an update to the NuGet. Instead of always relying on the package, check the local bot for it and use that as it will always be in sync.
=> Attempt to use the local ChromeDriver first

scripts/azure-templates-variables.yml
Run some nightly builds to ensure CI is always green when it is needed. Things might be getting out of date and we want to catch it.
=> Run nightly builds to ensure always green

binding/Binding/GRContext.cs, binding/Binding/SkiaApi.generated.cs, tests/Tests/GRContextTest.cs
Adding the `abandoned()` API to see if this might be something that could help #1642
**Bugs Fixed**
- Related to issue #1642
=> Expose IsAbandoned in the C# API

native/uwp/build.cake, source/SkiaSharp.Views/SkiaSharp.Views.UWP/AngleSwapChainPanel.cs
This swaps to the next buffer which is the new, correct size. When the size or scale changes, the new size is added to a "pending" variable and only gets pushed on the next frame. For render loop views, this is no problem, but for refresh-when-dirty views, we need to force the update by requesting the new buffer before drawing.
**Bugs Fixed**
- Fixes #1377
- Fixes #914
- Fixes #722
=> Swap the buffers after a resize

build.cake, scripts/azure-templates-bootstrapper.yml
Free up space be deleting samples as we go. Seems CI runs out of disk space with all the stuff we install and all the bits the compiler generates.
=> Free up space by deleting samples as they build

source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKCanvasView/SKCanvasViewHandler.iOS.cs
If there is no color set, then iOS can't clear it. As a result, the canvas is clear, but then it draws that clear canvas onto whatever there was before. And what was there before was the canvas so it keeps stacking things up.
This PR make sure that we let iOS know that it has to clear the underlying surface with transparent.
**Bugs Fixed**
An issue where the canvas never really cleared.
None.
None.
=> iOS requires that the view have a background

source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls/SKCanvasView.HandlerImpl.cs
protect null Handlers in .NET Maui SKCanvasView when invalidate the surface.
=> Fix NRE in .NET Maui SKCanvasView

scripts/install-vs.ps1
In some cases, the preview VS installer is older than the currently installed installer. As a result, the installer thinks it is already up to date.
This PR makes sure to always pull the latest installer, and then update to the very latest. This somehow makes the old installer install...
=> Ensure that VS is installed correctly

scripts/install-maui.ps1, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls/SKCanvasView.HandlerImpl.cs
Actions use a different method to trigger them.
- properties use `UpdateValue`
- actions use `Invoke` with optional args
=> Use Invoke for Actions

README.md, binding/HarfBuzzSharp/HarfBuzzSharp.csproj, binding/HarfBuzzSharp/nuget/build/android/HarfBuzzSharp.Local.targets, binding/HarfBuzzSharp/nuget/build/ios/HarfBuzzSharp.Local.targets, binding/HarfBuzzSharp/nuget/build/ios/HarfBuzzSharp.targets, binding/HarfBuzzSharp/nuget/build/maccatalyst/HarfBuzzSharp.Local.targets, binding/HarfBuzzSharp/nuget/build/maccatalyst/HarfBuzzSharp.targets, binding/HarfBuzzSharp/nuget/build/macos/HarfBuzzSharp.Local.targets, binding/HarfBuzzSharp/nuget/build/tvos/HarfBuzzSharp.Local.targets, binding/HarfBuzzSharp/nuget/build/tvos/HarfBuzzSharp.targets, binding/SkiaSharp/SkiaSharp.csproj, binding/SkiaSharp/nuget/build/android/SkiaSharp.Local.targets, binding/SkiaSharp/nuget/build/ios/SkiaSharp.Local.targets, binding/SkiaSharp/nuget/build/ios/SkiaSharp.targets, binding/SkiaSharp/nuget/build/maccatalyst/SkiaSharp.Local.targets, binding/SkiaSharp/nuget/build/maccatalyst/SkiaSharp.targets, binding/SkiaSharp/nuget/build/macos/SkiaSharp.Local.targets, binding/SkiaSharp/nuget/build/tvos/SkiaSharp.Local.targets, binding/SkiaSharp/nuget/build/tvos/SkiaSharp.targets, cake/xcode.cake, nuget/HarfbuzzSharp.nuspec, nuget/SkiaSharp.NativeAssets.MacCatalyst.nuspec, samples/Basic/Maui/SkiaSharpSample/SkiaSharpSample.csproj, scripts/azure-pipelines.yml, scripts/azure-templates-bootstrapper.yml, scripts/azure-templates-download.yml, scripts/azure-templates-linux-matrix.yml, scripts/azure-templates-wasm-matrix.yml
This PR adds the Mac Catalyst native component to the packages.
Previously this was having issues with the fact that the native framework has symlinks and .NET does not know how to handle that. It would end up duplicating files and then Xcode would not understand.
There are currently 2 issues that still affect this, and thus targets are required to patch it up a bit:
- https://github.com/xamarin/xamarin-macios/issues/11667
- https://github.com/xamarin/xamarin-macios/issues/12369
**Bugs Fixed**
- None
None
Code that would throw at runtime now does not.
=> Add Mac Catalyst support

nuget/HarfBuzzSharp.NativeAssets.WebAssembly.nuspec, nuget/SkiaSharp.NativeAssets.MacCatalyst.nuspec, nuget/SkiaSharp.NativeAssets.WebAssembly.nuspec
The file name of the .targets file for the SkiaSharp.NativeAssets.MacCatalyst package was not renamed to match the package ID and thus never got imported.
This is a bug in the PR #1760 
**Bugs Fixed**
- The .targets file for maccatalyst are not imported.
None.
Mac Catalyst compilation now works.
=> Use the correct MacCatalyst targets file name

binding/Binding/SKPaint.cs, tests/Tests/SKPaintTest.cs
@mattleibow
This is for compatibility and consistency. Before 2.80, the anti-aliasing flag would also affect the font edging. After 2.80, the properties were separate and now we have to make sure the paint updates the edging based on what the anti-aliasing and LCD rendering indicate.
**Bugs Fixed**
| 1.68.x | 2.80.x | PR |
| :-: | :-: | :-: |
| ![image](https://user-images.githubusercontent.com/1096616/132564635-8b0e485c-fd23-4415-a0d9-54930120d3f8.png) | ![image](https://user-images.githubusercontent.com/1096616/132564872-bf859b47-a694-415a-80d8-3b681831581f.png) | ![image](https://user-images.githubusercontent.com/1096616/132564945-cf215985-825d-4074-88da-33e66f5b0c57.png) |
```csharp
cnv.Clear(SKColors.White);
var paint = new SKPaint();
paint.TextSize = 40; …
```
=> IsAntialias should also control the Edging

native/tizen/build.cake, native/tizen/libSkiaSharp/project_def.prop, scripts/install-tizen.ps1
Previously I had used the new compiler AND new GCC to use the new features, however, it seems this may not have actually been working or we got lucky.
After upgrading to skia m88, I notice that the Tizen apps are no longer running. I think either m80 just did not make use of certain symbols in the newer glibc. However, with m88, this is now happening. It might have been a bit deceiving because the app may have launched and rendered content because libSkiaSharp is actually bundled on the Tizen device - at least my watch has it.
The new approach is to use the new compilers still, but the old GCC and work around the features needed in the code.
The even better solution would be to have 2 versions of the library built for different versions of Tizen. However, that is …
=> Build using the older gcc 6.2 and new llvm 10 compiler

SignList.xml, binding/SkiaSharp.UWP/SkiaSharp.UWP.csproj, native/uwp/build.cake, nuget/SkiaSharp.nuspec, samples/Basic/UWP/SkiaSharpSample/SkiaSharpSample.csproj, samples/Basic/Uno/SkiaSharpSample.UWP/SkiaSharpSample.UWP.csproj, samples/Basic/Xamarin.Forms/SkiaSharpSample.UWP/SkiaSharpSample.UWP.csproj, samples/Gallery/UWP/SkiaSharpSample/SkiaSharpSample.csproj, samples/Gallery/Uno/SkiaSharpSample.UWP/SkiaSharpSample.UWP.csproj, samples/Gallery/Xamarin.Forms/UWP/UWP.csproj, scripts/create-dummy-native.ps1
vcpkg bumped ANGLE here: https://github.com/microsoft/vcpkg/pull/18432
As a result, there was a new output file produced that needs to also be included in the package/apps.
**Bugs Fixed**
=> ANGLE now has another output zlib1.dll

source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls.Compatibility/SkiaSharp.Views.Maui.Controls.Compatibility.csproj, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls/SkiaSharp.Views.Maui.Controls.csproj, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/SkiaSharp.Views.Maui.Core.csproj
Context: https://github.com/jonathanpeppers/CustomResourceDesigner
Context: https://github.com/xamarin/xamarin-android/issues/6310
We found a case where a .NET MAUI app that included SkiaSharp and
Telerik controls was setting ~90,000 fields at startup in the
`Resource.designer.cs` file via the `UpdateIdValues()` method.
This also would happen in any Xamarin.Android class library:
* Include AndroidX & Google Material
* Include at least one `@(AndroidResource)` and use the ID from C#
* `Resource.designer.cs` has 2,700+ fields
So SkiaSharp is not unique to the problem here...
Reviewing the SkiaSharp fields, I found:
source\SkiaSharp.Views.Maui\SkiaSharp.Views.Maui.Controls\obj\Debug\net6.0-android\Resource.designer.cs
5335 fields …
=> [android] eliminate lots of fields in Resource.designer.cs

cake/msbuild.cake, nuget.config, scripts/azure-templates-bootstrapper.yml
=> Try this again

binding/Binding/SKColorSpace.cs, binding/Binding/SKData.cs, binding/Binding/SKFontManager.cs, binding/Binding/SKFontStyle.cs, binding/Binding/SKTypeface.cs, build.cake, tests/Tests/ApiTests.cs, tests/Tests/BaseTest.cs
When the AppDomain is unloaded, the runtime will try to dispose all instances, including ones on static fields. This might never happen in a single app, however, during test runs or potentially IDE integrations, the AppDomain is unloaded, the instances are collected and then SkiaSharp statics try to dispose of the native statics.
I originally had code to prevent the user from disposing the instances, however, the GC still runs and is still able to collect. So, for these few instances we mark it that we do not own the handles (which we don't) and then never even try clean up the instances. The GC will get to it.
**Bugs Fixed**
- Potential crashes when AppDomains are unloaded.
- Appears in #1817 when we get a GC collection out of expected order. …
=> Never dispose the native statics

binding/HarfBuzzSharp/nuget/build/maccatalyst/HarfBuzzSharp.Local.targets, binding/HarfBuzzSharp/nuget/build/maccatalyst/HarfBuzzSharp.targets, binding/SkiaSharp/nuget/build/maccatalyst/SkiaSharp.Local.targets, binding/SkiaSharp/nuget/build/maccatalyst/SkiaSharp.targets
This PR correctly handles the incremental builds of the mac catalyst targets. Previously, the entire task was skipped if the stamp file existed.
However, if for some reason the native file in the bin folder was deleted, then the task never ran again. This is because technically the target was ready, we just need to re-create the items. So to do this we set the targets file as the import and the stamp as the output. Then, MSBuild will do its thing and ensure that no _tasks_ run, just the properties and items are set.
**Bugs Fixed**
- Fixes an issue where deleting the Frameworks folder (or items in it) in the .app in the bin folder would cause an error. 
=> Fix the Mac Catalyst build task Inputs/Outputs

source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/SKCanvasView.razor.cs
Prevents infinite resize loop - i don't know if this is the most elegant solution, but it works.
Added the following line to `OnSizeChanged` Event of Blazor `SKCanvasView`
```csharp
if (Math.Round(canvasSize.Width * dpi) == newSize.Width && Math.Round(canvasSize.Height * dpi) == newSize.Height)
return;
```
If  Monitor scaling is applied in Windows Settings App, the view keeps multiplying the canvas size with the DPI (in my case being 1.25 for 125% scaling) in the `Invalidate`-Method. 
The Canvas will be resized to the new size which results in the `SizeWatcherInterop` to fire its `OnSizeChanged` Event which will set `canvasSize` to `newSize` and calls `Invalidate` again to start infinite loop, also mentioned here: …
=> [Blazor] prevent infinite loop in SKCanvasView

VERSIONS.txt, samples/Basic/Maui/SkiaSharpSample/SkiaSharpSample.csproj, samples/Basic/WinUI/Msix/SkiaSharpSample/SkiaSharpSample.csproj, samples/Basic/WinUI/WapProj/SkiaSharpSample.Package/SkiaSharpSample.Package.wapproj, samples/Basic/WinUI/WapProj/SkiaSharpSample/SkiaSharpSample.csproj, samples/Directory.Build.targets, scripts/azure-pipelines.yml, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKCanvasViewRendererBase.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKCanvasView/SKCanvasViewHandler.Android.cs, source/SkiaSharp.Views.WinUI/SkiaSharp.Views.WinUI/SkiaSharp.Views.WinUI.csproj, source/SkiaSharp.Views/SkiaSharp.Views.Apple/SKCGSurfaceFactory.cs, source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/iOSExtensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.Mac/MacExtensions.cs
=> Update to Maui Preview 11

VERSIONS.txt, samples/Basic/Uno/SkiaSharpSample.Android/SkiaSharpSample.Android.csproj, samples/Basic/Uno/SkiaSharpSample.Shared/App.xaml.cs, samples/Basic/Uno/SkiaSharpSample.Wasm/SkiaSharpSample.Wasm.csproj, samples/Basic/Uno/SkiaSharpSample.iOS/SkiaSharpSample.iOS.csproj, samples/Basic/Uno/SkiaSharpSample.macOS/SkiaSharpSample.macOS.csproj, samples/Gallery/Uno/SkiaSharpSample.Android/SkiaSharpSample.Android.csproj, samples/Gallery/Uno/SkiaSharpSample.Gtk/SkiaSharpSample.Gtk.csproj, samples/Gallery/Uno/SkiaSharpSample.Shared/App.xaml.cs, samples/Gallery/Uno/SkiaSharpSample.WPF.Host/SkiaSharpSample.WPF.Host.csproj, samples/Gallery/Uno/SkiaSharpSample.WPF/SkiaSharpSample.WPF.csproj, samples/Gallery/Uno/SkiaSharpSample.Wasm/SkiaSharpSample.Wasm.csproj, samples/Gallery/Uno/SkiaSharpSample.iOS/SkiaSharpSample.iOS.csproj, samples/Gallery/Uno/SkiaSharpSample.macOS/SkiaSharpSample.macOS.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Android/SkiaSharp.Views.Uno.Android.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Mac/SkiaSharp.Views.Uno.Mac.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Reference/SkiaSharp.Views.Uno.Reference.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Skia/SkiaSharp.Views.Uno.Skia.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SkiaSharp.Views.Uno.Wasm.csproj, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.iOS/SkiaSharp.Views.Uno.iOS.csproj
This change bumps Uno to 4.0 preview bits, which include binary breaking changes.
**Bugs Fixed**
None
None
Nonoe.
=> Bumps to Uno 4.0

binding/SkiaSharp/nuget/build/monoandroid/SkiaSharp.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/5776
Fixes: https://github.com/xamarin/xamarin-android/issues/6545
If you do:
1. File -> New Xamarin.Android class library
2. Add `<PackageReference Include="SkiaSharp" Version="2.80.3" />`
You end up with 13MB `.dll` file with C# code inside! The class
library is redistributing the SkiaSharp native libraries.
`$(ShouldIncludeNativeSkiaSharp)` should default to `False` for class
libraries.
To test this change, I manually edited:
%userprofile%\.nuget\packages\skiasharp\2.80.3\build\monoandroid1.0\SkiaSharp.targets
%userprofile%\.nuget\packages\skiasharp\2.80.3\buildTransitive\monoandroid1.0\SkiaSharp.targets
Now my class library is 76,800 bytes.
When consuming this class library in an Android application project,
everything should …
=> [android] don't include .so files in class libraries

scripts/azure-pipelines.yml, scripts/install-dotnet-workloads.ps1
Update to the new .NET Maui Preview 13 bits.
=> Build with Maui Preview 13

cake/msbuild.cake
Try resolve the intermittent build fails when using multiple threads on macOS/Linux.
**Bugs Fixed**
- Related to issue https://github.com/actions/virtual-environments/issues/4948
=> Force a single CPU on macOS/Linux

scripts/azure-pipelines.yml, scripts/azure-templates-build.yml, scripts/azure-templates-download.yml, scripts/azure-templates-linux-matrix.yml, scripts/azure-templates-wasm-matrix.yml
This PR just move the build infrastructure to a different set of agents other than the public, default, hosted Azure VMs.
=> Make use of the newer/better/faster/more-er 1ES build agents

scripts/azure-pipelines.yml, scripts/azure-templates-build.yml, scripts/install-dotnet-workloads.ps1
It appears that the workload installer randomly selects a feed to use to download packages.
I think I got a case where a version existed on both feeds - but as part of a separate build - one of which was signed and the other not.
This PR makes sure that if it is not a preview version of .NET, then it does not use the preview version of the workloads.
=> Skip the preview feed if not on a preview .NET

binding/Binding.Shared/LibraryLoader.cs
Newer Linux distributions (like Ubuntu 21.04) no longer ship with libdl.so, instead they have libdl.so.2
Try loading the newer lib first to fix issues like https://github.com/dotnet/maui/discussions/6385
Ideally we'd be using the [NativeLibrary.Load](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.load?view=net-6.0) API but we target netstandard2.0 here so we can't do that.
=> LibraryLoader: Try p/invoking to libdl.so.2 before libdl.so on Linux

native/uwp/build.cake, native/windows/build.cake, scripts/install-llvm.ps1
Some tools updated and we are not ready for it. The VC toolset 14.3 requires LLVM 13, so we need to go back down.
Requires: https://github.com/mono/skia/pull/86
=> Fix CI after VS updates

binding/Binding/SKBitmap.cs, tests/Tests/SKBitmapTest.cs
It appears the `SKBitmap` constructor can construct a 0x0 bitmap and be fine. However crashes on negative values. Improve the method by just returning null if the bounds are invalid as there is no way it can ever work.
**Bugs Fixed**
- Fixes #2012
=> Return null on invalid resize bounds

scripts/azure-pipelines-complete.yml, scripts/azure-pipelines-tests.yml, scripts/azure-pipelines.yml, scripts/azure-templates-bootstrapper.yml, scripts/azure-templates-build.yml, scripts/azure-templates-download.yml, scripts/azure-templates-linux-matrix.yml, scripts/azure-templates-stages.yml, scripts/azure-templates-wasm-matrix.yml
This PR tries to make builds easier for external contributors.
There are now 3 pipelines:
1. **azure-pipelines-complete.yml**  
For any contributor to use when setting up a custom pipeline to build SkiaSharp - and is also what we will use when we set up a public CI build.
3. **azure-pipelines.yml**  
For the first step in the split pipeline that _just_ builds binaries and creates [signed] NuGet packages.
4. **azure-pipelines-tests.yml**  
For the second step in the split pipeline that _just_ runs tests and compiles samples using the packages from the first step.
=> Make pipelines better

scripts/azure-templates-bootstrapper.yml, scripts/azure-templates-download-artifacts.yml
Adds download/upload tasks retry for CI pipeline
**Bugs Fixed**
none
None.
None.
None.
=> ci: add retries for dowload and upload tasks

source/SkiaSharp.Build.props, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKCanvasView/SKCanvasViewHandler.Tizen.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKImageSourceService/SKImageSourceService.Tizen.cs
Adding `SKCanvasViewHander.Tizen` and `SKImageSourceService.Tizen`.
=> [Tizen] Add SKCanvasViewHander and SKImageSourceService

binding/SkiaSharp/SkiaSharp.csproj, nuget/SkiaSharp.Views.Maui.Controls.Compatibility.nuspec, nuget/SkiaSharp.Views.Maui.Controls.nuspec, nuget/SkiaSharp.Views.Maui.Core.nuspec, nuget/SkiaSharp.Views.nuspec, nuget/SkiaSharp.nuspec, samples/Basic/Maui/SkiaSharpSample/Platforms/Tizen/Main.cs, samples/Basic/Maui/SkiaSharpSample/Platforms/Tizen/tizen-manifest.xml, samples/Basic/Maui/SkiaSharpSample/SkiaSharpSample.csproj, source/SkiaSharp.Build.props, source/SkiaSharp.Build.targets, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKCanvasViewRendererBase.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Native.Shared/SKGLViewRendererBase.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Tizen/SKCanvasViewRenderer.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Tizen/SKGLViewRenderer.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Tizen/SKImageSourceHandler.cs, source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Tizen/SKTouchHandler.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls.Compatibility/AppHostBuilderExtensions.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls.Compatibility/SkiaSharp.Views.Maui.Controls.Compatibility.csproj, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls/SkiaSharp.Views.Maui.Controls.csproj, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKCanvasView/SKCanvasViewHandler.Tizen.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKImageSourceService/SKImageSourceService.Tizen.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Platform/Tizen/SKCanvasViewExtensions.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/SkiaSharp.Views.Maui.Core.csproj, source/SkiaSharp.Views/SkiaSharp.Views/SkiaSharp.Views.csproj
This PR adds the Tizen TFM to various project groups:
- SkiaSharp
- SkiaSharp.Views
- SkiaSharp.Views.Maui
=> Add the net6.0-tizen TFM

binding/Directory.Build.targets, binding/HarfBuzzSharp.Classic/HarfBuzzSharp.Classic.csproj, binding/HarfBuzzSharp/HarfBuzzSharp.csproj, binding/SkiaSharp.Classic/SkiaSharp.Classic.csproj, binding/SkiaSharp/SkiaSharp.csproj, nuget/HarfBuzzSharp.NativeAssets.Win32.nuspec, nuget/HarfBuzzSharp.NativeAssets.macOS.nuspec, nuget/HarfbuzzSharp.NativeAssets.Linux.nuspec, nuget/HarfbuzzSharp.nuspec, nuget/SkiaSharp.HarfBuzz.nuspec, nuget/SkiaSharp.NativeAssets.Linux.NoDependencies.nuspec, nuget/SkiaSharp.NativeAssets.Linux.nuspec, nuget/SkiaSharp.NativeAssets.Win32.nuspec, nuget/SkiaSharp.NativeAssets.macOS.nuspec, nuget/SkiaSharp.Skottie.nuspec, nuget/SkiaSharp.Vulkan.SharpVk.nuspec, nuget/SkiaSharp.nuspec, source/SkiaSharp.Build.props, source/SkiaSharp.Build.targets, source/SkiaSharp.Vulkan/SkiaSharp.Vulkan.SharpVk/SkiaSharp.Vulkan.SharpVk.csproj, source/SkiaSharpSource.Windows-net6.slnf
Adds the base support for nullable reference types.
This also adds the "newer" TFMs to the list so that we can start to migrate to that and eventually drop the older ones.
New TFMs:
- netstandard2.1 (for all the netstandard people to get new nullable things)
- netcoreapp3.1 (the baseline for new .net)
- net5.0 (mainly for winui apps as they tend to be net5 from templates
- net6.0 (the future)
=> Add support for nullable and add newer TFMs

binding/SkiaSharp.Skottie/Animation.cs, binding/SkiaSharp.Skottie/SkottieApi.generated.cs, tests/Tests/Skottie/AnimationTest.cs
On Android, the streams for the Assets are not seekable - and the same with streams from the internet. So in order to actually read those, we first need to read the whole thing into a memory buffer.
This is not as expensive as it may sound as this is what happens internally. In C++, the full stream is read into a SKData instance, so pre-doing it in C# is the same thing. In fact, doing it via a data instance in C# opens up the potential to reduce the number of times we hop the interop boundary.
**Bugs Fixed**
None.
```cs
class Animation {
public static Animation? Create (SKData data);
public static bool TryCreate (SKData data, out Animation? animation);
}
```
Non-seekable streams can now be used to create animations. …
=> [skottie] Handle non-seekable streams

binding/Binding/SKData.cs, tests/Tests/SKDataTest.cs
This PR makes `SKData.AsStream()` a writeable stream so that it can be used to write to the data object.
**Bugs Fixed**
None.
None.
Makes the stream returned by `SKData.AsStream()` writeable.
None.
=> Make the SKDataStream writeable like SKData

binding/SkiaSharp.SceneGraph/SkiaSharp.SceneGraph.csproj, binding/SkiaSharp.Skottie/SkiaSharp.Skottie.csproj, nuget/SkiaSharp.Skottie.nuspec
Adds the missing targets for net6.0 ios, android, catalyst, macos, tvos, tizen for Skottie.
**Bugs Fixed**
None.
None.
None.
=> fix: Add net6.0 ios, android, catalyst, macos, tvos, tizen for Skottie

VERSIONS.txt
Every time the C API changes, we need to bump the C API increment. The last change (skottie) changed it.
**Bugs Fixed**
None.
None.
None.
https://github.com/mono/skia/pull/94
=> The C API is incremented

scripts/Docker/alpine/amd64/Dockerfile, scripts/Docker/alpine/amd64/build-local.sh, scripts/Docker/debian9/amd64/build-local.sh, scripts/Docker/debian9/clang-cross/build-local.sh, scripts/Docker/wasm/build-local.sh
=> Fix Alpine builds

binding/Binding/PlatformLock.cs
Fix for the `AccessViolationException` thrown from the finalizer thread when trying to deregister a handle after the `NonAlertableWin32Lock` has already been finalized.
**Bugs Fixed**
- Fixes #2194 
None.
No longer throws an uncatchable `AccessViolationException` from the finalizer thread.
None.
=> Don't try to enter/exit a critical section that has been deleted

binding/Binding/SKFontManager.cs, binding/Binding/SKTypeface.cs, binding/Binding/SkiaApi.generated.cs, binding/libSkiaSharp.json
I change the string input argument from `string` to IntPtr. The `sk_fontmgr_match_family_style` should input the `utf8` encoding string, but we will input the Unicode16 string to it. That is why we can not load the font which the font name contains the unicode text, such as the Chinese font.
**Bugs Fixed**
- Fixes #1914
None.
Now, we can load the font which the font name contains unicode text, such as the Chinese font.
None.
=> Fix load the font which the name contains unicode text

samples/Directory.Build.props
Force use Uno's Roslyn hosted generators instead of Uno.SourceGeneration tasks, even when LangVersion below 9.0. The original issue is caused by https://github.com/unoplatform/uno/issues/9297, resulting in :
```
MSBUILD : error : Generation failed: System.MissingMethodException: 
Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.
```
**Bugs Fixed**
None.
None.
None.
=> fix: Force use Uno's Roslyn hosted generators instead of Uno.SourceGeneration tasks

binding/Binding.Shared/PlatformConfiguration.cs
In some situations (or maybe Godot does something) looking for the libc library using the library name without the prefix causes issues.
**Bugs Fixed**
- Fixes #2200
None.
None.
None.
=> Use the full library name of libc

nuget.config, scripts/azure-pipelines-variables.yml, scripts/install-dotnet-workloads.ps1, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls.Compatibility/AppHostBuilderExtensions.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls.Compatibility/SkiaSharp.Views.Maui.Controls.Compatibility.csproj, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKCanvasView/SKCanvasViewHandler.Tizen.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKImageSourceService/SKImageSourceService.Tizen.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Platform/Tizen/SKCanvasViewExtensions.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Platform/Tizen/SKTouchHandler.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/SkiaSharp.Views.Maui.Core.csproj, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/CustomRenderingView.nui.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKCanvasView.nui.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKGLSurfaceView.nui.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SkiaSharp.Views.Tizen.csproj
This PR replace Tizen backend graphics engine for MAUI handlers
Tizen backend graphics engine will be changed on this [PR](https://github.com/dotnet/maui/pull/9619)
This PR is preparing it
* I add target framework net6-tizen on SkiaSharp.Views.Tizen project and it is supporting a new graphics engine called as NUI
* I remove tizen code on SkiaSharp.Views.Maui.Controls.Compatibility because Tizen New grapchis engine not support maui.controls.compatibility
Test with locally referencing with MAUI on this [PR](https://github.com/dotnet/maui/pull/9619)
**Bugs Fixed**
- Fixes #
None.
None.
None.
=> [Tizen] Change tizen graphics backend engine

source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Reference/nuget/build/netstandard2.0/SkiaSharp.Views.Uno.targets, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Reference/nuget/build/netstandard2.0/SkiaSharp.Views.Uno.WinUI.targets
Fixes this build issue appearing when using `SkiaSharp.Views.Uno.WinUI` or `SkiaSharp.Views.Uno.UI`:
```
Microsoft.Common.CurrentVersion.targets(5128,5): error MSB3025: 
The source file ".nuget\packages\skiasharp.nativeassets.webassembly\2.88.1\build\netstandard1.0\libSkiaSharp.a" is actually a directory. 
```
where `Content` property is filled regardless of the current target being compiled.
This particular block is properly included here:
https://github.com/mono/SkiaSharp/blob/2ad29861d5a40d3bf78c28ab0a9cb02a8f0fe437/binding/SkiaSharp/nuget/build/wasm/SkiaSharp.targets#L4-L6
None.
None.
None.
=> fix: Remove unused native library block from SkiaSharp.Views.Uno.UI/WinUI

source/SkiaSharp.Views/SkiaSharp.Views.Apple/AppleExtensions.cs, tests/SkiaSharp.iOS.Tests/iOSExtensionsTests.cs
`SKRect.ToRect()` does not convert to `CGRect` correctly.
**Bugs Fixed**
- Fixes #2242
None.
None.
None.
=> Convert SKRect to CGRect correctly

binding/Binding.Shared/LibraryLoader.cs
By default, internal dependences of a library loaded with `dlopen` are resolved using the global lookup scope first. If there are already matched symbols in the global scope, internal calls in the library that are supposed to use its local functions, will be linked to some external code, which is usually results in segmentation faults when the library is used. This is particularly true for the `libharfbuzz.so.0`, that is often present in the system, exports the same symbols as `libHarfBuzzSharp.so` and is implicitly used by some dependencies of `mono` or `dotnet`. To avoid such conflicts, there is a flag RTLD_DEEPBIND in `glibc` since version 2.3.4. Earlier versions do not check the mode argument for unknown flags, and `musl` does not check it either. So just …
=> Add RTLD_DEEPBIND flag to dlopen mode

native/.gitignore, native/uwp/build.cake, scripts/azure-templates-bootstrapper.yml
Previously I would download my own vcpkg and use that - then they added it to the image. As of a few weeks ago, there is now a new variable: https://github.com/actions/runner-images/pull/6218
**Bugs Fixed**
- Fixes https://github.com/microsoft/vcpkg/issues/26818
None.
None.
None.
=> Fix the use of vcpkg

native/wasm/build.cake, scripts/azure-templates-stages.yml, scripts/azure-templates-wasm-matrix.yml
- Adds 3.1.12 Emscripten single-threaded support (Aligned with .NET 7 RC1)
- Adds support for SIMD feature build
**Bugs Fixed**
None.
None.
None.
None.
=> feat: Generate for Emscripten 3.1.12 and SIMD features

nuget/SkiaSharp.Views.Blazor.nuspec, source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/Internal/SKHtmlCanvasInterop.cs, source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/nuget/build/net6.0/SkiaSharp.Views.Blazor.Local.props, source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/nuget/build/net6.0/SkiaSharp.Views.Blazor.props, source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/nuget/build/net6.0/SkiaSharpGLInterop.js, source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/wwwroot/SKHtmlCanvas.ts
As a result of the GL and GLctx instance not being exposed by default in .NET 7 (https://github.com/dotnet/runtime/issues/76077), we can hook into the setup of dotnet.js and then use that captured instance.
**Bugs Fixed**
- Fixes #2267
None.
None.
None.
=> Intercept and capture GL for .NET

binding/SkiaSharp/nuget/build/wasm/SkiaSharp.props
Fixes the globbing pattern used for 3.1.12 lookups, as now there are subfolders to discriminate builds based on runtime features.
**Bugs Fixed**
None.
None.
None.
=> fix(wasm): Adjust for invalid globbing for 3.1.12 archive lookup

VERSIONS.txt, source/SkiaSharp.Build.targets
Seems the newer .NET 6 SDK brings in newer dependencies and .NET 7 does not like that.
**Bugs Fixed**
- Fixes #2271
- Fixes #2272
None.
None.
None.
=> Force an older version of the Windows SDK

binding/HarfBuzzSharp/nuget/build/wasm/HarfBuzzSharp.props, binding/SkiaSharp/nuget/build/wasm/SkiaSharp.targets, native/wasm/build.cake, scripts/azure-pipelines-variables.yml, scripts/azure-templates-stages.yml, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SKSwapChainPanel.Wasm.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SKXamlCanvas.Wasm.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/WasmScripts/SkiaSharp.Views.Uno.Wasm.js
Adds explicit support for multi-threaded and SIMD combinations.
**Bugs Fixed**
- Parts #2285, still requires .NET SDK-specific adjustments.
- Fixes incorrect UWP type name for Uno Wasm
- Adds support for software rendering in Browser secure context (Used with threads)
- GL, GLctx and threading fixes (related to https://github.com/dotnet/runtime/issues/76077)
None.
None.
None.
=> feat(wasm): Add mt and mt+simd, fix harfbuzz for emsdk 3.1.12

source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKCanvasView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKCanvasView.nui.cs
- Fixes Canvas size calculation
- When use IgnorePixelScaling, a pixel based canvas size was convert to scaled pixel
- but, decimal part was cut by casting int, it cause error of size
**Bugs Fixed**
- Fixes #
None.
None.
None.
=> [Tizen] Fixes Canvas Size calculation

scripts/install-dotnet.ps1
Attempts to install .NET 6.0.403 have been failing on various jobs:
Error: Unable to download https://dotnetcli.blob.core.windows.net/public/Sdk/6.0.403/dotnet-dev-win-x64.6.0.403.zip. Returned HTTP status code: 404
Could not find ".NET Core SDK" with version = 6.0.403
Fix this by preferring the default feed found in the dotnet-install.ps1 script.
=> [ci] Use default feed to install the .NET SDK

source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.iOS/SKSwapChainPanel.iOS.cs
set to non opaque for consistency
=> Set Uno iOS SKSwapChainPanel to non-opaque for consistency

source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Mac/SKXamlCanvas.macOS.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.iOS/SKXamlCanvas.iOS.cs
See canvas default opacity to none on mac and iOS to align on other platforms.
**Bugs Fixed**
None.
By default, canvas will be transparent instead of black.
None.
=> [Uno] Default Opaque to false for SKXamlCanvas on MacOS and iOS

scripts/azure-templates-github-status.yml
This PR just allows the status updates to be skipped if we don't have a token.
=> Skip updating GitHub status when no token is available

nuget/SkiaSharp.Views.nuspec, source/SkiaSharp.Build.targets, source/SkiaSharp.Views/SkiaSharp.Views.Android/SKCanvasView.cs
**Bugs Fixed**
- Fixes #2444
None.
None.
None.
=> Ship the .aar with the NuGet for android

.config/dotnet-tools.json, cake/xcode.cake, native/ios/build.cake, native/macos/build.cake, native/tvos/build.cake, native/watchos/build.cake, scripts/azure-pipelines-variables.yml, scripts/install-vs.ps1
This PR prepares the cake files for the upcoming mac catalyst and arm64 things.
=> Update Cake files to override deployment targets

scripts/azure-pipelines-variables.yml, scripts/azure-templates-bootstrapper.yml, scripts/install-dotnet-workloads.ps1
The Tizen workload seems to have a bug where all the default os versions are bumped to 8 so that net6.0-tizen is now implicitly net6.0-tizen8. 0
There are some workarounds, such as using an explicit version or updating the manifest, but I am just going to use the older version of the package for now.
=> Install a specific Tizen version

scripts/azure-pipelines-variables.yml, scripts/azure-templates-bootstrapper.yml, scripts/install-dotnet-workloads.ps1
This PR just installs the .NET 7 SDK onto the agents. The libraries are still producing .NET 6 binaries.
=> Install .NET 7

source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs
Add an additional check to prevent exception. See related topics:
[[Bug] ImgeButtonRenderer used with Effect is disposed before calling OnDetach which may cause exception #13889](https://github.com/xamarin/Xamarin.Forms/issues/13889)
[Fix ObjectDisposedException issues for renderers OnElementPropertyChanged #9764](https://github.com/xamarin/Xamarin.Forms/pull/9764)
Since it's used in single place I think it's not worth creating/copying all these extensions from XF source.
Tests aren't provided cause it's not easy to replicate the exception.
**Bugs Fixed**
- Fixes #1614 
None.
None.
None.
=> [Android] Additional check to avoid ObjectDisposedException

scripts/azure-pipelines-cve.yml, scripts/guardian/cve-triage.json
Add a pipeline to run cve-bin-tool so we can detect any security issues with the binaries.
=> Run cve-bin-tool

binding/Binding/SKColor.cs
Improve performance of hex string parsing in SKColor using spans when available and with fewer allocated strings when spans are not supported.
- **ParseOld** is the current implementation for parsing hex strings to SKColor.
- **ParseImproved** is the improved parsing logic for platforms/frameworks that don't support spans
- **ParseSpan** is the new parsing logic using spans to avoid allocating strings
```
|        Method |                  Job |              Runtime |          Mean |      Error |     StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|-------------- |--------------------- |--------------------- |--------------:|-----------:|-----------:|------:|--------:|-------:|----------:|
|      ParseOld |             .NET 6.0 |             .NET 6.0 | 1,663.7469 …
```
=> Improve performance of hex string parsing in SKColor

native/wasm/build.cake, scripts/azure-templates-stages.yml
Enables Wasm EH and SIMD by default for Emscripten 3.1.34 (net8)
**Bugs Fixed**
- Fixes https://github.com/mono/SkiaSharp/issues/2494
None.
None.
None.
=> fix(wasm): Enable Wasm EH and SIMD in all configurations for net8+

source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/nuget/build/net6.0/SkiaSharp.Views.Blazor.Local.props, source/SkiaSharp.Views.Blazor/SkiaSharp.Views.Blazor/nuget/build/net6.0/SkiaSharp.Views.Blazor.props
Now that we have the new WASM assets, this PR will make sure that installing the SkiaSharp.Views.Blazor package correctly includes the assets for net6-8.
=> Include the new WASM assets in Blazor for .NET 8

nuget/SkiaSharp.Views.Uno.WinUI.nuspec
Fixes incorrect resolution for uno.winui target, because of missing `net7.0-*` targets.
None.
None.
None.
=> fix: Adjust net7.0-* resolution for Uno.WinUI targets

source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKGLView.cs
Disambiguates `SKGLView` native type when using Uno and MAUI concurrently.
None.
None.
None.
=> fix: Disambiguate SKGLView for uno and maui targets

binding/Binding/SKDocument.cs, binding/Binding/SKDrawable.cs, binding/Binding/SKFontManager.cs, binding/Binding/SKFontStyleSet.cs, binding/Binding/SKImage.cs, binding/Binding/SKManagedStream.cs, binding/Binding/SKPath.cs, binding/HarfBuzzSharp.Shared/Blob.cs, binding/HarfBuzzSharp.Shared/Buffer.cs, source/SkiaSharp.HarfBuzz/SkiaSharp.HarfBuzz.Shared/SKShaper.cs, source/SkiaSharp.Views/SkiaSharp.Views.Android/AndroidExtensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.Apple/AppleExtensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.Apple/SKCanvasLayer.cs, source/SkiaSharp.Views/SkiaSharp.Views.AppleiOS/SKCanvasView.cs, source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SKCanvasView.cs, source/SkiaSharp.Views/SkiaSharp.Views.UWP/UWPExtensions.cs, source/SkiaSharp.Views/SkiaSharp.Views.WPF/WPFExtensions.cs
Purely syntactic changed for improved readability
None.
None.
None.
=> Removing nesting levels through block-scoped `using` statement

binding/HarfBuzzSharp/nuget/build/ios/HarfBuzzSharp.targets, binding/SkiaSharp/nuget/build/ios/SkiaSharp.targets
Some versions of .NET do not automatically copy NativeReferences from the runtimes/ios/native folder in Hot Restart scenarios. This PR makes sure to always include it.
**Bugs Fixed**
- Fixes #
None.
None.
None.
=> Include the NativeReference for Hot Restart

source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Wasm/WasmScripts/SkiaSharp.Views.Uno.Wasm.js
Ensures the that the GL context is current when rendering for a given SKSwapChainPanel, allowing for multiple instances to be rendered correctly in an app.
**Bugs Fixed**
- Fixes https://github.com/mono/SkiaSharp/issues/2551
None.
None.
None.
=> fix(uno): Ensure that the canvas' context is active when rendering

binding/SkiaSharp/MathTypes.cs, tests/Tests/SkiaSharp/SKBasicTypesTest.cs
Truncation will chop off parts, and this will lose value. Flooring outwards ensure that the size touches the edge of the containing rect. This is useful that any partial overhang with integer sizes can be clipped when drawing.
**Bugs Fixed**
- Fixes #2562
None.
None.
None.
=> Floor outwards when converting to SKRectI

tests/Tests/SkiaSharp/SKFontTest.cs, tests/Tests/SkiaSharp/SKPaintTest.cs
These tests are loading a custom typeface from a file and assigned to the paint and font Typeface properties. This is to ensure nothing obvious is going wrong.
**Related Issues**
- Related to #2572
None.
None.
None.
=> Add some more specific tests

scripts/guardian/cve-triage.json
There is a CVE report `CVE-2023-25193` of libjpeg being used, however, it is not and the libjpeg-turbo is used instead. In addition, the libjpeg-turb codebase is from the time the issue was fixed - and it was not a security issue.
See more: https://github.com/libjpeg-turbo/libjpeg-turbo/issues/500#issuecomment-772625597
=> libjpeg is not used

native/ios/build.cake
Apple doesn't allow submissions with that architecture. In this PR I will just comment it out and when it is ready for use I will add it back.
**Bugs Fixed**
- Fixes #2584
None.
None.
None.
=> Remove the unused arm64e architecture

.devcontainer/devcontainer.json, .devcontainer/packages.sh, .vscode/settings.json
Just going to make getting started much easier.
=> Set up dev containers

native/wasm/build.cake, scripts/azure-templates-stages.yml
This change re-introduces no-SIMD WebAssembly native assets, in order for apps be able to work around SIMD not being supported by Microsoft Edge Enhanced Security. 
Related to https://github.com/dotnet/runtime/issues/78872 and https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/774.
**Bugs Fixed**
None.
None.
None.
=> fix: Restore nosimd builds for edge enhanced security and safari

scripts/azure-pipelines-variables.yml
It appears that after the Azure DevOps image was updated, some packages are no longer on the box. This PR will re-install them for the Tizen installer/SDK.
=> Install missing Tizen packages after image update

scripts/install-android-ndk.ps1
No idea why, but adding `-verbose` makes the image attach, at least in my CI testing...
=> Fix Android NDK extraction

source/SkiaSharp.Build.targets
Long versions make nuget.org very sad.
=> NuGet versions need to be < 64 characters

source/SkiaSharp.Views/SkiaSharp.Views.Shared/GlesInterop/Gles.cs
Do not provide invalid externs as they may cause issues later on or with code that scans assemblies for valid functions.
**Bugs Fixed**
- API Scan warnings/errors
None.
None.
None.
=> Hide functions that opengl32.dll does not actually have

source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Shared/SKXamlCanvas.cs
The async void will terminate here. And we can ignore the Dispatcher.RunAsync result and we can receive the exception from TaskScheduler.UnobservedTaskException.
See https://github.com/dotnet/runtime/issues/76367
**Bugs Fixed**
- Fixes https://github.com/unoplatform/uno/issues/15123
None.
In the original behavior, if the `SKXamlCanvas.Invalidate` method is called in the background thread, it will be scheduled back to the main thread through the `Dispatcher.RunAsync` method. However, if any business code throws an exception in the `PaintSurface` event, it will cause the process to crash.
After the modification, if business code throws an exception in the `PaintSurface` event, the exception will be received in …
=> Avoid async void in SKXamlCanvas.

binding/Binding.Shared/PlatformConfiguration.cs
Previously SkiaSharp used old APIs to conditionally execute platform specific APIs. Specifically, RuntimeInformation.IsOSPlatform is known to be non-trimmable.
It caused some Windows PInvokes to be included in the non-windows binaries. For most platform it didn't really cause any problems, but apparently tvOS linker is more sensitive (see #2715)
This PR changes PlatformConfiguration class:
1.  Use newer trimmer friendly `OperatingSystem.IsWindows()` method instead of non-trimmable `RuntimeInformation.IsOSPlatform (OSPlatform.Windows)`.
2. Remove static ctor, and instead move these checks to the property getters. 
On .NET6+ targets with trimmer enabled these calls will be eliminated and values will be inlined.
Non trimmed SkiaSharp:
Trimmed SkiaSharp with "-r …
=> Make PlatformConfiguration properties trimmable (fixes tvOS compilation)

scripts/azure-templates-stages.yml
Some smaller agents run out of storage with all the symbols.
=> Split the packaging job

binding/NativeAssets.Build.targets, binding/SkiaSharp.NativeAssets.WinUI/SkiaSharp.NativeAssets.WinUI.csproj
The managed dlls used by references need to be in the lib sub-folder, not native.
=> Correctly package managed runtime-only files

binding/SkiaSharp/SKImage.cs, binding/SkiaSharp/SkiaApi.generated.cs, tests/Tests/SkiaSharp/SKImageTest.cs
**Bugs Fixed**
- Fixes #2338
```cs
public SKShader ToRawShader ();
public SKShader ToRawShader (SKShaderTileMode tileX, SKShaderTileMode tileY)
public SKShader ToRawShader (SKShaderTileMode tileX, SKShaderTileMode tileY, SKMatrix localMatrix)
public SKShader ToRawShader (SKShaderTileMode tileX, SKShaderTileMode tileY, SKSamplingOptions sampling);
public SKShader ToRawShader (SKShaderTileMode tileX, SKShaderTileMode tileY, SKSamplingOptions sampling, SKMatrix localMatrix);
```
None.
https://github.com/mono/skia/pull/119
=> Add SKImage.ToRawShader

source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKGLView/SKGLViewHandler.MacCatalyst.cs, source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI/SkiaSharp.Views.Uno.WinUI.csproj, source/SkiaSharp.Views/SkiaSharp.Views.Shared/GlesInterop/Gles.cs, source/SkiaSharp.Views/SkiaSharp.Views.Shared/SKPaintGLSurfaceEventArgs.cs, source/SkiaSharp.Views/SkiaSharp.Views/Platform/Apple/SKPaintMetalSurfaceEventArgs.cs
There is no OpenGL or OpenGL ES on Mac Catalyst - there technically _is_ but it is not meant to be used - so we swap out the backend of the .NET MAUI `SKGLView` to rather be a `SKMetalView` on Mac Catalyst.
There needs to be a new GPU view that uses Metal on Apple and maybe Vulkan on Android. But that is for another PR. We need an interface so people can even swap out their preferred backend. https://github.com/mono/SkiaSharp/issues/2104
=> Use Metal as a backend on Mac Catalyst

scripts/azure-templates-bootstrapper.yml, scripts/azure-templates-stages.yml
- Use the correct agent
- Fix retries
=> Improve compliance jobs

binding/Directory.Build.targets, binding/SkiaSharp/SKMatrix44.cs, tests/Tests/SkiaSharp/SKMatrix44Tests.cs
Using `Unsafe.As` provides almost double the perf improvement - see the issue.
**Bugs Fixed**
- Fixes #2778
None.
None.
https://github.com/mono/skia/pull/120
=> Use Unsafe.As for better perf

scripts/azure-pipelines-complete-internal.yml, scripts/azure-pipelines-complete.yml, scripts/azure-pipelines-cve.yml, scripts/azure-pipelines-tests.yml, scripts/azure-pipelines.yml, scripts/azure-templates-bootstrapper.yml, scripts/azure-templates-linux-matrix.yml, scripts/azure-templates-stages.yml, scripts/azure-templates-wasm-matrix.yml
=> Use full template specifications

scripts/azure-pipelines-complete-internal.yml, scripts/azure-pipelines.yml, scripts/azure-templates-bootstrapper.yml, scripts/azure-templates-linux-matrix.yml, scripts/azure-templates-merger.yml, scripts/azure-templates-stages.yml, scripts/azure-templates-wasm-matrix.yml, scripts/install-python.ps1
Another day, another compliance day.
=> Clean up APIScan and other compliance yaml

binding/Binding/SKImageFilter.cs
In SkiaSharp 3.x, the overloads no longer take the `SKImageFilter.CropRect` and instead use a plain `SKRect`.
This PR adds a bunch of overloads into the 2.x series that are present in 3.x - notably the `SKImageFilter.CropRect` to `SKRect` as well as some others. `CreateShader` is also new and really `CreatePaint` is a `CreateShader` under the hood in C++.
For the variations of `CreateMatrix` with the different `in` overloads, I will add this back into 3.x using the mechanism in https://github.com/mono/SkiaSharp/pull/2789
Instead of a single overload with all the default parameters, the new overloads avoid defaults so we can not require nullable structs as well as not use the `CropRect` class if the crop rect is not in use.
After this PR lands, libraries that want …
=> [release/2.x] Add some new overloads for better compat

binding/SkiaSharp/SKRunBuffer.cs, binding/SkiaSharp/SKTextBlob.cs, source/SkiaSharp.HarfBuzz/SkiaSharp.HarfBuzz/CanvasExtensions.cs, tests/Tests/SkiaSharp/SKTextBlobTest.cs
This is sort of inspired by #2664 but also the `SKRunBuffer` API is a bit weird. In 2.x the skia comments say the text part is not meant to be sued, but it is actually required in some cases.
I had cleaned up the API a bit before, but I see I still needed some work. 
Then #2664 was asking for less allocations, so I am thinking instead of spans, we just return the struct directly (almost) and then it is up to the caller to do the right thing. 
- Fixes https://github.com/mono/SkiaSharp/issues/2776
=> Clean up SKTextBlobBuilder and SKRunBuffer APIs

source/SkiaSharp.Views/SkiaSharp.Views/Platform/Apple/SKMetalView.cs
**Bugs Fixed**
Fixed bug when Flush() -> Snapshot() returns magenta color when using Apple Metal backend. Affects any backdrop logic.
Before / after
Credits to react/google folks: https://groups.google.com/g/skia-discuss/c/FTO0NSR_09Q/m/U0jO5E35AgAJ
None.
None.
None.
=> Fix Snapshot returning magenta color Apple Metal

binding/NativeAssets.Build.targets, binding/SkiaSharp/SKCanvas.cs, binding/SkiaSharp/SKImageFilter.cs, binding/SkiaSharp/SKPath.cs, binding/SkiaSharp/SkiaSharp.csproj, changelogs/SkiaSharp/3.0.0/SkiaSharp.humanreadable.md, source/SkiaSharp.Build.props, source/SkiaSharp.Build.targets, source/SkiaSharp.NuGet.targets
In SkiaSharp 3.0 we are focusing on performance and making use of new APIs and structures.
However, we can add a few compatibility things back to make upgrades much simple/easier.
- Part of https://github.com/mono/SkiaSharp/issues/2790
=> Add and remove the compatibility APIs

binding/SkiaSharp/GRDefinitions.cs
Just a few missing `readonly` modifiers of the property getters.
=> GRMtlTextureInfo should have readonly getters

binding/SkiaSharp.Resources/ResourcesApi.generated.cs, binding/SkiaSharp.SceneGraph/SceneGraphApi.generated.cs, binding/SkiaSharp.Skottie/SkottieApi.generated.cs, binding/SkiaSharp/SKBlender.cs, binding/SkiaSharp/SKColorSpace.cs, binding/SkiaSharp/SKData.cs, binding/SkiaSharp/SKFontManager.cs, binding/SkiaSharp/SKImageFilter.cs, binding/SkiaSharp/SKObject.cs, binding/SkiaSharp/SKPaint.cs, binding/SkiaSharp/SKRuntimeEffect.cs, binding/SkiaSharp/SKShader.cs, binding/SkiaSharp/SKTypeface.cs, binding/SkiaSharp/SkiaApi.generated.cs, changelogs/SkiaSharp/3.0.0/SkiaSharp.humanreadable.md, tests/Tests/GarbageCleanupFixture.cs, tests/Tests/SkiaSharp/SKBlenderTest.cs
`SKBlender` represents a custom blend function in the Skia pipeline. 
When a blender is present in a paint, the `BlendMode` property is ignored. A blender combines a source color (the result of our paint) and destination color (from the canvas) into a final color.
**Bugs Fixed**
None.
```cs
// NEW TYPES
public unsafe class SKBlender : SKObject, ISKReferenceCounted
{
public static SKBlender CreateBlendMode (SKBlendMode mode);
public static SKBlender CreateArithmetic (float k1, float k2, float k3, float k4, bool enforcePMColor);
}
public class SKRuntimeBlenderBuilder : SKRuntimeEffectBuilder
{
public SKRuntimeBlenderBuilder (SKRuntimeEffect effect);
public SKBlender Build ();
}
// NEW MEMBERS
class SKImageFilter
{
public static SKImageFilter …
```
=> Expose SKBlender

native/winui/ANGLE.cake, scripts/cake/shared.cake
The tool brings in dependencies which we don't want, so just use the URI directly to get the file. Specifically https://github.com/GoogleCloudPlatform/gsutil/issues/1478
According to Google, none of the risky dependencies are used and should be dropped, but to satisfy the machines we can just skip the entire process and download the file ourselves.
=> Remove usage of `gsutil`

binding/SkiaSharp/SKDrawable.cs, binding/SkiaSharp/SKPicture.cs, binding/SkiaSharp/SkiaApi.generated.cs, tests/Tests/SkiaSharp/SKDrawableTest.cs, tests/Tests/SkiaSharp/SKPictureTest.cs
Adding a few new APIs to help with determining picture and drawable "size" as well as adding the `Playback` method to `SKPicture`.
The playback method is different to draw in that draw results in a single "draw the picture" command, but playback effectively replicates what was done to create the picture. There is a small different to the latter in that the picture may optimize/combine commands as well as split commands to best fit into the picture's storage.
**Bugs Fixed**
- Fixes #2881
```cs
class SKDrawable {
public int ApproximateBytesUsed { get; }
}
class SKPicture {
public int ApproximateBytesUsed { get; }
public int ApproximateOperationCount { get; }
public int GetApproximateOperationCount(bool includeNested);
public void Playback(SKCanvas …
```
=> Add more SKPicture APIs

binding/SkiaSharp/SKTypeface.cs
The SkTypeface::getKerningPairAdjustments API states:
> If count is non-zero, then the glyphs parameter must point to at least [count] valid glyph IDs, and the adjustments parameter must be sized to at least [count - 1] entries. If the method returns true, then [count-1] entries in the adjustments array will be set. If the method returns false, then no kerning should be applied, and the adjustments array will be in an undefined state (possibly some values may have been written, but none of them should be interpreted as valid values). 
However, `SkTypeface.GetKerningPairAdjustments` returns `count` entries _and further_ in the case where `getKerningPairAdjustments` returns false it may return invalid values to the caller. This PR:
* Adds a `Span`-based overload of …
=> Fix the GetKerningPairAdjustments API.

binding/SkiaSharp/SKPictureRecorder.cs, binding/SkiaSharp/SkiaApi.generated.cs, tests/Tests/SkiaSharp/SKPictureRecorderTest.cs
Add the R-Tree overload of `SKPicture.BeginRecording`. 
The R-Tree factory type (`SkRTreeFactory`) or any other `SkBBHFactory` types are not exposed since it is fairly complicated and not many use cases. It can be added later. For now, we just have a boolean flag indicating whether to use it or not.
**Bugs Fixed**
- Fixes https://github.com/mono/SkiaSharp/issues/2372
```cs
class SKPicture {
public SKCanvas BeginRecording (SKRect cullRect, bool useRTree);
}
```
None.
https://github.com/mono/skia/pull/129
=> Add R-Tree overload of beginRecording

source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Skia/SKXamlCanvas.Skia.cs
Use Bgra8888 instead of PlatformColorType
**Bugs Fixed**
When not running on Windows where PlatformColorType may not be Bgra8888, rendering will be incorrect. In Uno, both WriteableBitmap and SkiaCompositionSurface deal explicitly with Bgra8888, so the format used in SKXamlCanvas has to match.
https://github.com/unoplatform/uno/blob/1d1f8c9f1f87fbb7e1af9d884049cef06cb46680/src/Uno.UI.Composition/Composition/SkiaCompositionSurface.skia.cs#L64
None.
None.
None.
=> Fix SKXamlCanvas on Uno Skia to use Bgra8888

binding/SkiaSharp/SKCanvas.cs
Use the `SKPaint.FilterQuality` for the `SKSamplingOptions` in obsolete methods. In SkiaSharp 3.0, the `SKPaint.FilterQuality` property is obsolete (removed from the underlying skia API) but we still need to use that value if no sampling options are provided.
**Bugs Fixed**
- Fixes #
None.
None.
None.
=> Use SKPaint.FilterQuality instead of SKSamplingOptions.Default

source/SkiaSharp.Views/SkiaSharp.Views.WinUI/SKXamlCanvas.cs
When a view is resized, the canvas is not yet resized and updated to match. Before this PR, the canvas would be stretched to fill the view. This PR make sure to not stretch the canvas but instead keep it fixed.
The reason for the scaling in the first place is that `WriteableBitmap` does not have a DPI parameter. As a result, we have to create a larger bitmap than the view such that when it is scaled down to match the view size, the resolution matches that of the rest of the app. Previously, the larger canvas was just squashed to fit, but this was non-uniform. This PR always scales the canvas to the correct size preserving the aspect ratio.
**Bugs Fixed**
- None.
None.
None.
None.
=> Do not stretch the background

scripts/install-tizen.ps1
Tizen Studio is failing almost all the time on Linux:
```
Install destination is '/home/cloudtest/tizen-studio'...
Downloading SDK to '/home/cloudtest/tizen-temp/tizen-install.bin'...
Validating Java install...
JAVA_HOME is: /usr/lib/jvm/temurin-11-jdk-amd64
PATH contains JAVA_HOME: False
openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment Temurin-11.0.23+9 (build 11.0.23+9)
OpenJDK 64-Bit Server VM Temurin-11.0.23+9 (build 11.0.23+9, mixed mode)
Installing SDK to '/home/cloudtest/tizen-studio'...
setting up jdk at /home/cloudtest/.package-manager/jdk
rm: cannot remove '/home/cloudtest/.package-manager/jdk': No such file or directory
./installer.sh: 4: Syntax error: "(" unexpected
Installing Additional Packages: 'MOBILE-6.0-NativeAppDevelopment'... …
```
=> Update Tizen Studio

scripts/azure-templates-stages.yml
Skip the Tizen build because it keeps failing on Linux. We are using the Windows build and also have a macOS build.
**Bugs Fixed**
- Fixes https://github.com/mono/SkiaSharp/issues/2933
=> Skip building Tizen on Linux

binding/SkiaSharp/SKRoundRect.cs
This allows stackalloc-ed arrays to be passed.
**Bugs Fixed**
- Fixes #
None.
None.
None.
=> Provide Span overload for SetRectRadii

source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls/SKGLView.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKCanvasView/SKCanvasViewHandler.Apple.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKGLView/SKGLViewHandler.MacCatalyst.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKGLView/SKGLViewHandler.iOS.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Platform/Apple/SKEventProxy.cs, source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Platform/Apple/SKTouchHandlerProxy.cs, tests/SkiaSharp.Tests.Devices.Mac.sln, tests/SkiaSharp.Tests.Devices/MauiProgram.cs, tests/SkiaSharp.Tests.Devices/SkiaSharp.Tests.Devices.csproj, tests/SkiaSharp.Tests.Devices/Tests/Maui/MauiExtensions.cs, tests/SkiaSharp.Tests.Devices/Tests/Maui/MemoryLeakTests.cs, tests/SkiaSharp.Tests.Devices/Tests/Maui/SKUITests.cs, tests/Tests/Xunit/AssertEx.cs
It is very easy to create a circular reference in iOS and we had a few. When you have an event from a platform view to another instance that then references that platform view, you get an un-collectable set.
This PR breaks this chain by making the platform view have an event on a proxy object that has a _weak_ reference to handlers and/or virtual views.
**Bugs Fixed**
- Fixes #2923
None.
None.
None.
=> Fix memory leaks in MAUI views

binding/SkiaSharp/GRGlInterface.cs, scripts/azure-templates-stages.yml, source/SkiaSharp.Build.props
After #2950 landed, the native artifacts were not downloaded and included in the general native collection step.
=> Make sure ANGLE reaches the nugets

binding/SkiaSharp/SKBitmap.cs, binding/SkiaSharp/SKImage.cs, binding/SkiaSharp/SKPaint.cs, binding/SkiaSharp/SKShader.cs
Libraries may want to remain supporting both SkiaSharp 2.x and 3.x, as we currently do in Uno Platform.
We achieve this by detecting the assembly version and using UnsafeAccessor when needed for APIs that have changed in SkiaSharp 3.
However, there is one remaining issue for Uno Platform, which is SKFilterQuality. As the overloads now take SKSamplingOptions which is a completely new type in SkiaSharp 3, we can't use UnsafeAccessor to get this to work.
This PR adds new obsolete APIs that accepts SKFilterQuality and forwards it to the SKSamplingOptions overload. For Uno Platform, we will use `paint.FilterQuality` when on 2.x, and use the new shader overloads via UnsafeAccessor when on 3.x
NOTE: This is applicable for any library that needs to remain on 2.x while allowing consumers to …
=> Add compatibility overloads for SKFilterQuality

samples/Basic/WPF/SkiaSharpSample/SkiaSharpSample.csproj, samples/Basic/WindowsForms/SkiaSharpSample/SkiaSharpSample.csproj, source/SkiaSharp.Build.props, source/SkiaSharp.Views/SkiaSharp.Views.WPF/SkiaSharp.Views.WPF.csproj, source/SkiaSharp.Views/SkiaSharp.Views.WindowsForms/SKGLControl.cs, source/SkiaSharp.Views/SkiaSharp.Views.WindowsForms/SkiaSharp.Views.WindowsForms.csproj, source/SkiaSharp.Views/SkiaSharp.Views/SkiaSharp.Views.csproj
Use the new packaged for the new TFMs - like we have for WPF.
**Bugs Fixed**
- Fixes #1803
None.
None.
None.
=> Use the new GLControl packages for WinForms

scripts/azure-pipelines-variables.yml, scripts/install-dotnet-workloads.ps1
~I fell asleep and CI broke.~
The maui rollback files are now hosted in the maui repository instead of the blob storage.
=> Fix CI again

binding/SkiaSharp/SKPixmap.cs
Reverts `SKBitmap.Encode` to previous behavior to use default PNG compression.
Until 2.88.8: ZLibLevel 6 is used for PNG compression.
Since 3.0.0:  ZLibLevel 0 is used for PNG compression.
**Bugs Fixed**
- Fixes #3013
None.
Calling `SKBitmap.Encode` or `SKPixmap.Encode (SKWStream, SKEncodedImageFormat, int)` will result in a default PNG compression level (as in 2.88.8). The `SKPngEncoderFilterFlags` are unchanged.
None.
=> Revert SKBitmap.Encode with SKPngEncoderOptions to previous behavior (2.88.8)

scripts/install-tizen.ps1
It appears that most of the older (< 6.0) tools have been removed from the "latest" package manager, so we need to use the snapshots.
See more: https://developer.tizen.org/blog/announcing-tizen-studio-6.0-release
> Added Tizen 9.0 profile and deprecated all Tizen profiles below 6.0.
_I have a feeling this may have been an error since some of the web tools are still there and the wording is "deprecated". But, either way, this will be more consistent for this old branch._
=> Use a snapshot now that 4.0 has been removed

.github/workflows/label-with-ai.yml
A small workflow to help label issues with the correct area, platform, backend, and tenet labels.
=> Add a workflow to auto label issues

source/SkiaSharp.Build.props
I think the SDK and/or VS updates have brought in some issue, but I think there is another way to do what we want.
We currently have this:
```xml
<FrameworkReference
Update="Microsoft.Windows.SDK.NET.Ref"
RuntimeFrameworkVersion="10.0.19041.27"
TargetingPackVersion="10.0.19041.27" />
```
But that is assuming the framework references are added early and we run late. But, it appears something changed and now the values are either ignored or the items are added in a different place. This results in our adjustments being ignored.
There is another property `<WindowsSdkPackageVersion>` that can be used and feels more official.
I think in net6 something broke with the property so we had to do it via the framework references, but now it appears they fixed it and broke …
=> Use `<WindowsSdkPackageVersion>` to set the SDK version

binding/HarfBuzzSharp.NativeAssets.WebAssembly/buildTransitive/HarfBuzzSharp.targets, binding/IncludeNativeAssets.SkiaSharp.targets, source/SkiaSharp.Views/SkiaSharp.Views.Blazor/nuget/buildTransitive/SkiaSharp.Views.Blazor.Local.props, source/SkiaSharp.Views/SkiaSharp.Views.Blazor/nuget/buildTransitive/SkiaSharp.Views.Blazor.props
The workaround needed for WASM is not really Blazor specific and if the project is not using the Blazor views, the fix will not be applied to the build.
The workaround for https://github.com/dotnet/runtime/issues/109289 was added in #3064, however because a project may not be using the SkiaSharp.Views.Blazor package it will still fail.
**Bugs Fixed**
- Fixes #3049
- FIxes https://github.com/mono/SkiaSharp/issues/3074
None.
None.
None.
=> Move the Blazor workaround into WASM

native/winui-angle/build.cake, scripts/azure-templates-bootstrapper.yml, scripts/azure-templates-stages.yml, scripts/get-free-space.ps1
The public bots are running out of space.
The MSVC compiler is so heavy that the outputs are over 10.8GB
whereas the LLVM compiler is just under 10.1GB.
The public agent only starts with 12GB and after the checkout we are
left with 10.67GB which is smaller than the 10.8GB required. The LLVM
compiler just manages to pass under the bar with about 600MB spare.
If the SkiaSharp artifacts get any bigger, then we will need custom
machines for the public build.
=> Log more information about disk space and skip the MSVC builds on public

native/android/build.cake, native/android/libHarfBuzzSharp/jni/Application.mk, native/android/libHarfBuzzSharp/jni/HarfBuzzSharp.mk, scripts/install-android-ndk.ps1
Update to the latest Android NDK and use the new alignment requirements.
**Bugs Fixed**
- Fixes #3025
None.
None.
None.
=> Update the Android NDK to r27c and update to 16kb alignment

binding/SkiaSharp/SKObject.cs
`SafeRef` should call  `sk_refcnt_safe_ref` instead `sk_refcnt_safe_unref`.
**Bugs Fixed**
Fix the incorrect behavior of `SafeRef`.
None.
None.
None.
=> Fix the incorrect call in SafeRef.

scripts/azure-templates-bootstrapper.yml, scripts/azure-templates-merger.yml, scripts/azure-templates-stages.yml, scripts/download-artifact.ps1
Public CI can't seem to download anymore
TODO: at some point we should add some checks to make sure all the artifacts in the matrix are also in the list.
=> Manually list all the artifacts to download

binding/SkiaSharp/GRBackendRenderTarget.cs, binding/SkiaSharp/GRDefinitions.cs, binding/SkiaSharp/GRMtlBackendContext.cs, source/SkiaSharp.Views/SkiaSharp.Views/Platform/Apple/SKMetalView.cs, source/SkiaSharp.Views/SkiaSharp.Views/Platform/Apple/SKPaintMetalSurfaceEventArgs.cs
Added support for `SKMetalView` on tvOS
**Bugs Fixed**
- Fixes https://github.com/mono/SkiaSharp/issues/3115
None.
None.
None.
=> Support `SKMetalView` on tvOS

source/SkiaSharp.Views/SkiaSharp.Views/Platform/Apple/SKMetalView.cs
This comes from a new synced branch.
Had iOS simulator lagging on M1 at 9 fps with SKGLView, so had to adjust its platform-related code for iOS to unlock 60 fps.
Just followed Apple guidelines for simulator:   https://developer.apple.com/documentation/metal/developing-metal-apps-that-run-in-simulator?language=objc
replacing `SampleCount = 1;` (no MSAA) inside `SKMetalView` with:
```csharp
if (DeviceInfo.Current.DeviceType == DeviceType.Virtual)
{
DepthStencilStorageMode = MTLStorageMode.Private;
SampleCount = 4;
}
else
{
DepthStencilStorageMode = MTLStorageMode.Shared;
SampleCount = 2;
}
```
Works fine in DrawnUi now, wanted to share.
=> Fix iOS Simulator performance with Metal

source/SkiaSharp.DotNet.Interactive/SkiaSharp.DotNet.Interactive.csproj
Context: https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
Bumps Microsoft.DotNet.Interactive to v1.0.0-beta.25110.2 to bring in
an updated version of System.Text.Json.
=> [build] Address CVE-2024-30105

binding/SkiaSharp.NativeAssets.Linux.NoDependencies/SkiaSharp.NativeAssets.Linux.NoDependencies.csproj, binding/SkiaSharp.NativeAssets.Linux/SkiaSharp.NativeAssets.Linux.csproj, binding/SkiaSharp.NativeAssets.NanoServer/SkiaSharp.NativeAssets.NanoServer.csproj, binding/SkiaSharp.NativeAssets.Win32/SkiaSharp.NativeAssets.Win32.csproj, binding/SkiaSharp.NativeAssets.macOS/SkiaSharp.NativeAssets.macOS.csproj
Starting with SkiaSharp 3.x only the `buildTransitive` directory is created for the NativeAssets NuGet packages. This breaks older .NET Framework projects that use `packages.config` instead of the newer `PackageReference`.
To retain backwards compatibility this PR copies the `net462\SkiaSharp.NativeAssets.*.targets` file into both `build` and `buildTransitive` (as it was for before in SkiaSharp 2.x).
**Bugs Fixed**
- Fixes #3111
- Fixes #3107
None.
None.
None.
=> Fix regression that breaks projects using .NET Framework/Mono and packages.config

binding/Binding.Shared/PlatformConfiguration.cs, binding/SkiaSharp/PlatformLock.cs, binding/SkiaSharp/SKAutoCoInitialize.cs
These APIs are fine to leave in for most cases, but I see tvOS fails AOT because it can't find the imports to Win32 things.
This PR just removes them entirely from Apple and Android builds as they will never exist. We have to leave it for the others because a net8.0 dll could run on macOS or Windows with GTK things,
=> Exclude code that will never run on Apple

binding/SkiaSharp/SKImage.cs, tests/Tests/SkiaSharp/SKImageTest.cs, tests/Tests/SkiaSharp/SKTest.cs
This PR bumps the externals/skia as that has a fix for passing null surface props: https://github.com/mono/skia/pull/156
However, it then also fixes the case where creating images from pictures requires a color space. If there is no color space, then null is returned. The docs say null color space is fine, but the code says otherwise. I asked the team to clarify: https://groups.google.com/g/skia-discuss/c/vbFCoMQXF3c
**Bugs Fixed**
- Fixes #3157
None.
None.
None.
=> Fix the SKImage.FromPicture implementation

scripts/azure-pipelines-native.yml
Restores the CI triggers to allow SkiaSharp-Native to run against main
and release branches.
=> [azure-pipelines-native] Add CI triggers for primary branches

scripts/azure-pipelines-native.yml, scripts/azure-pipelines-package.yml
Build everything every midnight. This will not only give us nightly builds, but also make sure CI is still working.
We also use this to generate all the compliance and security things. They take too long to run as part of the normal CI, so we run them at night.
=> Add a cron job to make sure all is well

scripts/azure-templates-variables.yml
Increase the build number in the new pipeline. The last build published to the preview feed was 38, but I saw a 41 in the logs. So, let's skip to 50.
=> Increase the build number in the new pipeline

source/SkiaSharp.Views/SkiaSharp.Views/Platform/Apple/SKMetalView.cs
Avoids creating `GRMtlBackendContext` twice (and the duplicate command queue)
**Bugs Fixed**
None.
None.
None.
=> Avoid initializing SKMetalView twice

binding/SkiaSharp/SKTypeface.cs, binding/SkiaSharp/SkiaApi.generated.cs, tests/Tests/SkiaSharp/SKTypefaceTest.cs
Added PostScriptName property to SkTypeface
**Bugs Fixed**
None.  Added a missing binding.
None.
Added: 
- `string SkTypeface.PostScriptName { get; set; }`
None.
None.
https://github.com/mono/skia/pull/158
=> Added PostScriptName to SkTypeface
